{
	"patcher" : 	{
		"fileversion" : 1,
		"appversion" : 		{
			"major" : 8,
			"minor" : 3,
			"revision" : 2,
			"architecture" : "x64",
			"modernui" : 1
		}
,
		"classnamespace" : "box",
		"rect" : [ 1079.0, 247.0, 152.0, 148.0 ],
		"bglocked" : 0,
		"openinpresentation" : 0,
		"default_fontsize" : 12.0,
		"default_fontface" : 0,
		"default_fontname" : "Arial",
		"gridonopen" : 1,
		"gridsize" : [ 15.0, 15.0 ],
		"gridsnaponopen" : 1,
		"objectsnaponopen" : 1,
		"statusbarvisible" : 2,
		"toolbarvisible" : 0,
		"lefttoolbarpinned" : 0,
		"toptoolbarpinned" : 0,
		"righttoolbarpinned" : 0,
		"bottomtoolbarpinned" : 0,
		"toolbars_unpinned_last_save" : 0,
		"tallnewobj" : 0,
		"boxanimatetime" : 200,
		"enablehscroll" : 0,
		"enablevscroll" : 0,
		"devicewidth" : 0.0,
		"description" : "",
		"digest" : "",
		"tags" : "",
		"style" : "",
		"subpatcher_template" : "",
		"assistshowspatchername" : 0,
		"globalpatchername" : "echoplex@1",
		"boxes" : [ 			{
				"box" : 				{
					"fontface" : 0,
					"format" : [ 1.2 ],
					"id" : "obj-9",
					"label" : [ "fb" ],
					"labelcolor" : [ 0.694117647058824, 0.0, 0.0, 1.0 ],
					"max" : 2.0,
					"maxclass" : "ll_number",
					"min" : 0.0,
					"mousefocus" : 1,
					"numinlets" : 1,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"parameter_enable" : 0,
					"patching_rect" : [ 0.0, 56.0, 152.0, 20.0 ],
					"slidermax" : 2.0,
					"textcolornofocus" : [ 0.694117647058824, 0.0, 0.0, 0.788235294117647 ],
					"varname" : "echoPlexFB"
				}

			}
, 			{
				"box" : 				{
					"annotation" : "ramp time between presets. click on ppooll in the ho_st to find info about it",
					"fontface" : 0,
					"fontsize" : 14.0,
					"format" : [ 10000, 1000, ":", 100, 10, 1 ],
					"id" : "obj-25",
					"maxclass" : "ll_number",
					"numinlets" : 1,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"parameter_enable" : 0,
					"patching_rect" : [ 0.0, 18.0, 81.0, 10.0 ],
					"varname" : "preset-ramp"
				}

			}
, 			{
				"box" : 				{
					"annotation" : "presets grid. click on ppooll in the ho_st to find info about it",
					"filename" : "ll.pattr_ui.js",
					"id" : "obj-24",
					"jsarguments" : [ 13, "255 255 255", "50 50 50", "255 0 0", "0 255 0", "delayloops1" ],
					"maxclass" : "jsui",
					"numinlets" : 1,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"parameter_enable" : 0,
					"patching_rect" : [ 83.0, 0.0, 69.0, 28.0 ],
					"varname" : "presets"
				}

			}
, 			{
				"box" : 				{
					"hidden" : 1,
					"id" : "obj-21",
					"maxclass" : "newobj",
					"numinlets" : 1,
					"numoutlets" : 3,
					"outlettype" : [ "", "", "" ],
					"patching_rect" : [ 358.5, 23.5, 123.0, 22.0 ],
					"restore" : [ "in(2)" ],
					"saved_object_attributes" : 					{
						"parameter_enable" : 0,
						"parameter_mappable" : 0
					}
,
					"text" : "pattr inputs~",
					"varname" : "inputs~[1]"
				}

			}
, 			{
				"box" : 				{
					"fontface" : 0,
					"format" : [ 3 ],
					"id" : "obj-33",
					"label" : [ "delay_time" ],
					"labelcolor" : [ 0.694117647058824, 0.0, 0.0, 1.0 ],
					"max" : 1000.0,
					"maxclass" : "ll_number",
					"min" : 1.0,
					"numinlets" : 1,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"parameter_enable" : 0,
					"patching_rect" : [ 0.0, 33.0, 152.0, 20.0 ],
					"slidermax" : 1000.0,
					"textcolornofocus" : [ 0.694117647058824, 0.0, 0.0, 0.788235294117647 ],
					"varname" : "echoPlexDelayTime"
				}

			}
, 			{
				"box" : 				{
					"bgmode" : 0,
					"border" : 1,
					"clickthrough" : 0,
					"enablehscroll" : 0,
					"enablevscroll" : 0,
					"id" : "obj-43",
					"lockeddragscroll" : 0,
					"lockedsize" : 0,
					"maxclass" : "bpatcher",
					"name" : "ll.blues.maxpat",
					"numinlets" : 1,
					"numoutlets" : 0,
					"offset" : [ 0.0, 0.0 ],
					"patching_rect" : [ 0.0, 94.0, 151.0, 53.0 ],
					"varname" : "ll.blues",
					"viewvisibility" : 1
				}

			}
, 			{
				"box" : 				{
					"bgmode" : 0,
					"border" : 0,
					"clickthrough" : 0,
					"enablehscroll" : 0,
					"enablevscroll" : 0,
					"id" : "obj-16",
					"lockeddragscroll" : 0,
					"lockedsize" : 0,
					"maxclass" : "bpatcher",
					"name" : "ll.inputmix.maxpat",
					"numinlets" : 0,
					"numoutlets" : 2,
					"offset" : [ 0.0, 0.0 ],
					"outlettype" : [ "multichannelsignal", "multichannelsignal" ],
					"patching_rect" : [ 0.0, 78.0, 152.0, 12.0 ],
					"varname" : "ll.inputmix",
					"viewvisibility" : 1
				}

			}
, 			{
				"box" : 				{
					"id" : "obj-18",
					"ignoreclick" : 1,
					"maxclass" : "lcd",
					"numinlets" : 1,
					"numoutlets" : 4,
					"outlettype" : [ "list", "list", "int", "" ],
					"patching_rect" : [ 0.0, 0.0, 81.0, 16.0 ],
					"varname" : "title_LCD"
				}

			}
, 			{
				"box" : 				{
					"color" : [ 0.0, 0.0, 0.0, 1.0 ],
					"fontname" : "Arial",
					"fontsize" : 12.0,
					"hidden" : 1,
					"id" : "obj-1",
					"maxclass" : "newobj",
					"numinlets" : 2,
					"numoutlets" : 0,
					"patching_rect" : [ 335.0, 108.0, 177.0, 22.0 ],
					"text" : "actmaker echoplex@ #ABB7C8",
					"varname" : "act"
				}

			}
, 			{
				"box" : 				{
					"color" : [ 0.0, 0.0, 0.0, 1.0 ],
					"fontname" : "Arial",
					"fontsize" : 12.0,
					"hidden" : 1,
					"id" : "obj-17",
					"maxclass" : "newobj",
					"numinlets" : 1,
					"numoutlets" : 1,
					"outlettype" : [ "multichannelsignal" ],
					"patcher" : 					{
						"fileversion" : 1,
						"appversion" : 						{
							"major" : 8,
							"minor" : 3,
							"revision" : 2,
							"architecture" : "x64",
							"modernui" : 1
						}
,
						"classnamespace" : "box",
						"rect" : [ 161.0, 153.0, 736.0, 712.0 ],
						"bglocked" : 0,
						"openinpresentation" : 0,
						"default_fontsize" : 12.0,
						"default_fontface" : 0,
						"default_fontname" : "Arial",
						"gridonopen" : 1,
						"gridsize" : [ 15.0, 15.0 ],
						"gridsnaponopen" : 1,
						"objectsnaponopen" : 1,
						"statusbarvisible" : 2,
						"toolbarvisible" : 1,
						"lefttoolbarpinned" : 0,
						"toptoolbarpinned" : 0,
						"righttoolbarpinned" : 0,
						"bottomtoolbarpinned" : 0,
						"toolbars_unpinned_last_save" : 0,
						"tallnewobj" : 0,
						"boxanimatetime" : 200,
						"enablehscroll" : 1,
						"enablevscroll" : 1,
						"devicewidth" : 0.0,
						"description" : "",
						"digest" : "",
						"tags" : "",
						"style" : "",
						"subpatcher_template" : "",
						"assistshowspatchername" : 0,
						"boxes" : [ 							{
								"box" : 								{
									"id" : "obj-8",
									"maxclass" : "newobj",
									"numinlets" : 1,
									"numoutlets" : 1,
									"outlettype" : [ "" ],
									"patching_rect" : [ 513.0, 318.0, 89.0, 22.0 ],
									"text" : "ll.r echoPlexFB"
								}

							}
, 							{
								"box" : 								{
									"id" : "obj-7",
									"maxclass" : "newobj",
									"numinlets" : 1,
									"numoutlets" : 1,
									"outlettype" : [ "" ],
									"patching_rect" : [ 388.5, 85.0, 131.0, 22.0 ],
									"text" : "ll.r echoPlexDelayTime"
								}

							}
, 							{
								"box" : 								{
									"id" : "obj-92",
									"linecount" : 2,
									"maxclass" : "comment",
									"numinlets" : 1,
									"numoutlets" : 0,
									"patching_rect" : [ 351.0, 570.0, 150.0, 33.0 ],
									"text" : "https://github.com/Rickr922/echoplex-sim"
								}

							}
, 							{
								"box" : 								{
									"id" : "obj-88",
									"linecount" : 4,
									"maxclass" : "comment",
									"numinlets" : 1,
									"numoutlets" : 0,
									"patching_rect" : [ 532.0, 205.0, 150.0, 74.0 ],
									"text" : "Slider(float): feedback[style:knob] [init=0.5:min=0:max=2:step=0.01:cur=0.5]\n"
								}

							}
, 							{
								"box" : 								{
									"id" : "obj-86",
									"linecount" : 3,
									"maxclass" : "comment",
									"numinlets" : 1,
									"numoutlets" : 0,
									"patching_rect" : [ 488.0, 126.0, 150.0, 60.0 ],
									"text" : "Slider(float): delay(ms) [init=300:min=1:max=1000:step=1:cur=300]\n"
								}

							}
, 							{
								"box" : 								{
									"format" : 6,
									"id" : "obj-63",
									"maxclass" : "flonum",
									"numinlets" : 1,
									"numoutlets" : 2,
									"outlettype" : [ "", "bang" ],
									"parameter_enable" : 0,
									"patching_rect" : [ 464.0, 213.0, 50.0, 22.0 ]
								}

							}
, 							{
								"box" : 								{
									"id" : "obj-62",
									"maxclass" : "message",
									"numinlets" : 2,
									"numoutlets" : 1,
									"outlettype" : [ "" ],
									"patching_rect" : [ 381.0, 267.0, 74.0, 22.0 ],
									"text" : "feedback $1"
								}

							}
, 							{
								"box" : 								{
									"format" : 6,
									"id" : "obj-61",
									"maxclass" : "flonum",
									"numinlets" : 1,
									"numoutlets" : 2,
									"outlettype" : [ "", "bang" ],
									"parameter_enable" : 0,
									"patching_rect" : [ 429.0, 156.0, 50.0, 22.0 ]
								}

							}
, 							{
								"box" : 								{
									"id" : "obj-59",
									"maxclass" : "message",
									"numinlets" : 2,
									"numoutlets" : 1,
									"outlettype" : [ "" ],
									"patching_rect" : [ 375.0, 196.0, 77.0, 22.0 ],
									"text" : "delay_ms $1"
								}

							}
, 							{
								"box" : 								{
									"id" : "obj-3",
									"library_path0" : "/Users/greg/Documents/Max 8/Packages/faustgen/externals/msp/faustgen~.mxo/Contents/Resources/",
									"machinecode" : "z/rt/gcAAAEDAAAAAQAAAAQAAAAIAgAAACAAAAAAAAAZAAAAiAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADdWAAAAAAAAKAIAAAAAAAA3VgAAAAAAAAcAAAAHAAAABAAAAAAAAABfX3RleHQAAAAAAAAAAAAAX19URVhUAAAAAAAAAAAAAAAAAAAAAAAA0TkAAAAAAAAoAgAABAAAAGBYAABLAAAAAAQAgAAAAAAAAAAAAAAAAF9fbGl0ZXJhbDgAAAAAAABfX1RFWFQAAAAAAAAAAAAA2DkAAAAAAADgAQAAAAAAAAA8AAADAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAX19saXRlcmFsMTYAAAAAAF9fVEVYVAAAAAAAAAAAAADAOwAAAAAAAHAAAAAAAAAA6D0AAAQAAAAAAAAAAAAAAA4AAAAAAAAAAAAAAAAAAABfX2NvbnN0AAAAAAAAAAAAX19URVhUAAAAAAAAAAAAADA8AAAAAAAABxoAAAAAAABYPgAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAADIAAAAYAAAAAQAAAAAADAAAAAAAAAAAAAIAAAAYAAAAuFoAAA4AAACYWwAAqBoAAAsAAABQAAAAAAAAAAEAAAABAAAABwAAAAgAAAAGAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAw2ZmZmZmZi4PH4QAAAAAAEFXQVZBVFNQSIn7x0ccAAAAAMX4V8DF+BGHaBAAAEjHh3gQAAAAAAAAxfgRh7AQAADF+BGHABEAAEjHhxARAAAAAAAAxfgRhzARAABIx4dAEQAAAAAAAMX4EYdgEQAASMeHcBEAAAAAAADF+BGHiBEAAMX4EYfYEQAASMeH6BEAAAAAAADF+BGHCBIAAEjHhxgSAAAAAAAAxfgRhzgSAABIx4dIEgAAAAAAAMX4EYdgEgAAxfgRh7ASAABIx4fAEgAAAAAAAMX4EYfgEgAATI13UEjHh/ASAAAAAAAAxfgRhxATAABIx4cgEwAAAAAAAEiBxzgTAABJvAAAAAAAAAAAvgAAAgBB/9RMjbtYEwIAxfhXwMX4EYOIEwoASMeDmBMKAAAAAAC+CBAAAEyJ90H/1MX4V8DF/BGDiBAAAL4gAAgATIn/xfh3Qf/USIPECFtBXEFeQV/DDx+EAAAAAABBVlNIgew4AQAASIn7iTfF+yrGSLjYOQAAAAAAAMX7EAjF+SlMJBDF+1/BSLjgOQAAAAAAAMX7XQDF+xGEJLAAAADF+xFHBMXzXsDF+SkEJEi46DkAAAAAAADF+1kASb4AAAAAAAAAAEH/1sX5KYQkIAEAAMX5KEwkEMXzXtDF+xGUJLgAAABIuPA5AAAAAAAAxetYAMTi6anBxfNewMX7EUMMSLj4OQAAAAAAAMX5KAQkxftZAEH/1sX5KGQkEMXbXshIuAA6AAAAAAAAxfsQEMXzWNrF217bxfsRWyDF61zRxfsRUyhIuAg6AAAAAAAAxfNYEEi4EDoAAAAAAADF+xAYxOLxqdPF217SxfsRUzDF+1nQSLgYOgAAAAAAAMX7ECDF217iSLggOgAAAAAAAMXbWCjF+xFrOEi4KDoAAAAAAADF+xCsJLAAAADF01koxfsRa0BIuDA6AAAAAAAAxfNYCEi4wDsAAAAAAADF+SgoxfkprCQQAQAAxONRDckBxfkUwsXxXsDF+VjLSLjQOwAAAAAAAMX5KBDF6VzAxON5DcEBxfkRg1gQAABIuDg6AAAAAAAAxfsQAMX7EUQkIEi4QDoAAAAAAADE4vmpIMX7EaOAEAAASLhIOgAAAAAAAMX5KAwkxfNZAMX7EYOoEAAASLhQOgAAAAAAAMXzWQBB/9bF+Sh0JBDFy17ISLhYOgAAAAAAAMX7EBDF+xGUJKgAAADF81jSxXtZyEi44DsAAAAAAADF+SggxfkppCQAAQAAxONZDdIBxMF5FOHF6V7USLhgOgAAAAAAAMX7ECDF6VjsxXkoxMX5KaQkwAAAAMXpWOLFyV7txfko3ki48DsAAAAAAADF+SgwxfkptCTwAAAAxclc9MTjSQ3tAcX5EavAEAAASLhoOgAAAAAAAMX7ECjF+xGsJKAAAADF81jtSLhwOgAAAAAAAMX7EDDE4vGp7sX5KP7F+xF0JDjF417txfsRq9AQAADE43kF0gFIuHg6AAAAAAAAxfsQKMX7EawkmAAAAMXrWO3F+xGr2BAAAEi4gDoAAAAAAADF+xAoxfsRrCSQAAAAxfNY7Ui4iDoAAAAAAADF+xAwxfsRtCSIAAAAxOLxqe7F417txfsRq+AQAABIuJA6AAAAAAAAxfsQKMX7EawkgAAAAMXzWO1IuJg6AAAAAAAAxbEUwMX7EBjF+SmcJNAAAADF4RTdxeFewEi4ADwAAAAAAADF+SgYxfkpnCTgAAAAxflY28X5EZvoEAAAxON5BdwBSLigOgAAAAAAAMX7ECDF+xFkJHjF21zjxfsRo/gQAABIuKg6AAAAAAAAxfsQIMX7EWQkcMTi2ZlEJCDF+xGDGBEAAEi4sDoAAAAAAADF+xAAxfsRRCRoxfNYwMTi8anHxfsRgyARAABIuLg6AAAAAAAAxfsQAMX7EUQkYMX7XMPF+xGDKBEAAEi4wDoAAAAAAADF+xAAxfsRRCRYxftcw8X7EYNIEQAASLjIOgAAAAAAAMX7EADF+xFEJFDF81jAxMLxqcDF+xGDUBEAAEi40DoAAAAAAADF+xAAxfsRRCRIxftcw8X7EYNYEQAASLjYOgAAAAAAAMX7EADF+xFEJEDF61jAxfsRg3gRAABIuOA6AAAAAAAAxfkoDCTF81kAxfsRg4ARAABIuOg6AAAAAAAAxfNZAEH/1sX5KHwkEMXDXsjF81iUJKgAAADF+1nYxONpDZQkAAEAAALF+RTjxele1MV5KIQkwAAAAMW5WOLF6VjqxcFe5MX5KLQk8AAAAMXJXPXE40kN5AHF+RGjmBEAAMXzWKQkoAAAAMX7EHQkOMTi8anmxcNe5MX7EaOoEQAAxON5BdIBxetYpCSYAAAAxfsRo7ARAADF81ikJJAAAADE4vGppCSIAAAAxcNe5MX7EaO4EQAAxeEUwMXzWJwkgAAAAMX5KKQk0AAAAMXZFNvF4V7AxflYnCTgAAAAxfkRm8ARAADE43kF3QHF+xBkJHjF21zjxfsRo9ARAADF+xBkJHDE4tmZRCQgxfsRg/ARAADF81hEJGjE4vGpxsX7EYP4EQAAxfsQRCRgxftcw8X7EYMAEgAAxfsQRCRYxftcw8X7EYMgEgAAxfNYRCRQxMLxqcDF+xGDKBIAAMX7EEQkSMX7XMPF+xGDMBIAAMXrWEQkQMX7EYNQEgAASLjwOgAAAAAAAMX5KAwkxfNZAMX7EYNYEgAASLj4OgAAAAAAAMXzWQBB/9bF+Sh8JBDFw17IxfNYlCSoAAAAxONpDZQkAAEAAALF+1nYxfkU48XpXtTFeSiMJMAAAADFsVjixcFe5MVpWMLF+Si0JPAAAADEwUlc8MTjSQ3kAcX5EaNwEgAAxfNYpCSgAAAAxfsQbCQ4xOLxqeXFw17kxfsRo4ASAADE43kF0gHF61ikJJgAAADF+xGjiBIAAMXzWKQkkAAAAMTi8amkJIgAAADFw17kxfsRo5ASAADF81ikJIAAAADF+Si0JNAAAADFyRTkxeEUwMXZXsDF+xBkJCDE4vmpZCRwxflYhCTgAAAAxfkRg5gSAADEw3kFwAHF+xBcJHjF41zYxfsRm6gSAADF+xGjyBIAAMXzWFwkaMTi8andxfsRm9ASAADF+xBcJGDF41zYxfsRm9gSAADF+xBcJFjF41zYxfsRm/gSAADF81hcJFDEwvGp2cX7EZsAEwAAxfsQTCRIxfNcwMX7EYMIEwAAxetYRCRAxfsRgygTAABIuAA7AAAAAAAAxfsQhCSwAAAAxftZAMX7EYMwEwAASLgIOwAAAAAAAMX5KAQkxftZAEi4AAAAAAAAAAD/0MX7EYM4EwIAxfkoTCQQxfNcwMX7EYNAEwIAxfsSBCRIuBA8AAAAAAAAxflZAMX5KUQkIEm+AAAAAAAAAABB/9bF+SkEJMTjeQVEJCABQf/WxfkoDCTF8RTAxfkRg0gTAgBIuBA7AAAAAAAAxfsQhCS4AAAAxftYAMX5KJQkIAEAAMXrWcrF+SicJBABAADE42ENwAHF6RTJxflewcX5WEwkEMXhXMDE43kNwQHF+RGDeBMKAEiBxDgBAABbQV7DDx8Aw2ZmZmZmZi4PH4QAAAAAAMNmZmZmZmYuDx+EAAAAAABIuAAAAAAAAAAAww8fRAAAVUFXQVZBVUFUU0iB7EgBAACF9g+O9i4AAEiJ+0iLAkiJhCTYAAAASIsBSImEJNAAAABIi0EISImEJMgAAADF+xBPSEi4GDsAAAAAAADF+xAASLggOwAAAAAAAMTi8akAxfsswIlEJBRBifVEi2cci4dUEAAARTH2SLkoOwAAAAAAAMX7EAHF+xGEJMAAAABIuTA7AAAAAAAAxfsQAcX7EYQkuAAAAEi5ODsAAAAAAADF+xABxfsRhCSwAAAASLlAOwAAAAAAAMX7EAHF+xFEJAhIuUg7AAAAAAAAxfsQAcX7EYQkqAAAAEm/AAAAAAAAAABIuVA7AAAAAAAAxfsQAcX7EYQkoAAAAEi5WDsAAAAAAADF+xABxfsRhCSYAAAASLlgOwAAAAAAAMX7EAHF+xGEJJAAAABIuWg7AAAAAAAAxfsQAcX7EYQkiAAAAEi5cDsAAAAAAADF+xABxfsRhCSAAAAASLl4OwAAAAAAAMX7EAHF+xFEJHhIuYA7AAAAAAAAxfsQAcX7EUQkcEi5iDsAAAAAAADF+xABxfsRRCRoSLkgPAAAAAAAAMX4KAHF+CmEJDABAABIuZA7AAAAAAAAxfsQAcX7EUQkYEi5mDsAAAAAAABIuqA7AAAAAAAASL6oOwAAAAAAAEi/sDsAAAAAAADF+xABxfsRRCRYxfsQAsX7EUQkUMX7EAbF+xFEJEjF+xBDFMX7EUQkQMX7EUwkGMXzWUNAxfsRRCQ4xfsQo3gQAADF+xCzcBAAAMX7EJOgEAAAxXsQq5AQAADF+xCDuBAAAMV7EJsQEQAAxfsQuwgRAADFexCTQBEAAMX7EKs4EQAAxXsQg3ARAADFexCLaBEAAMV7ELOQEQAAxfsQD8X7EUwkMA8fhAAAAAAARInhgeH/AQAAxfsQTCQYxfsRTMtQacBtTsZBBTkwAACJg1AQAADFGyrgxfsQSzDF21mbWBAAAMTiybmbYBAAAMXjWdnE4pm7XCQ4xfsRm2gQAADFy1mzgBAAAMXjWNzE4smZWzjF+xGbiBAAAMXrWVMoxZNY28Ti8avaxeNZSyDF+xFMJCDF+xGLmBAAAMX7EIuoEAAAxftY0cTjaQvSCcX7XMLF+1jBxfsRg7AQAADF+xCL4BAAAMWjWZPwEAAAxOLBuZP4EAAAxetZ0cTimbuUJMAAAADF+xGTABEAAMXDWZsYEQAAxaNY0sTi4ZmT6BAAAMX7EJvQEAAAxatZoyARAADE4tG5oygRAADF21njxOLxu+LF+xGjMBEAAMXTWYtIEQAAxatY5MTi8Zmj2BAAAMW7WZNQEQAAxOKxuZNYEQAAxXsQk8AQAADF+xCrgBEAAMWrWdLE4uG71MX7EZNgEQAAxYtY3cTjYQvbCcWLXNvF41jNxfsRDCTF+xGLiBEAAMX7EJu4EQAAxfsQo+gRAADF21mryBEAAMX7ELPgEQAAxOLJuavQEQAAxdNZ68TimbusJLgAAADF+xGr2BEAAMXLWbPwEQAAxdNY5MTiyZmjwBEAAMX7EKuoEQAAxfsQsxgSAADFy1m7+BEAAMX7EIsQEgAAxOLxubsAEgAAxcNZ/cTi4bv8xfsRuwgSAADF81mLIBIAAMXDWN7E4vGZm7ARAADF+xCLSBIAAMX7EYwkIAEAAMXzWYsoEgAAxfsQo5gRAADF+xGkJBgBAADF+xCzQBIAAMX7EbQkEAEAAMTiybmLMBIAAMXzWczE4tG7y8X7EYwkCAEAAMX7EYs4EgAAxfsQi1gSAADF+xCbaBIAAMXjWOHE41kL5AnF41zcxeNYycX7EYwkKAEAAMX7EYtgEgAAxfsQi8ASAADF81mboBIAAMX7EKO4EgAAxOLZuZuoEgAAxfsQq5ASAADF41ndxOKZu5wksAAAAMX7EZuwEgAAxdtZo8gSAADF41jJxOLZmYuYEgAAxfsQm/ASAADF41mj0BIAAMX7ELPoEgAAxOLJuaPYEgAAxfsQu4ASAADF21nnxOLRu+HF+xGj4BIAAMXLWYv4EgAAxdtY28Ti8ZmbiBIAAMX7EIsgEwAAxfsRjCT4AAAAxfNZiwATAADF+xCjGBMAAMX7EaQk8AAAAMTi2bmLCBMAAMX7EKNwEgAAxfsRpCQAAQAAxfNZ5MTiwbvjxfsRpCTgAAAAxbtYysX7EaMQEwAAxbNZk8gQAADE4umZi3gRAADF+xBUJAjE4umphCSoAAAAxOKpucFB/9fF+1mEJKAAAADF+xGEJOgAAADF+xAUJMX7EEQkCMTi+amUJJgAAADF+xCEJBABAADF+1mLoBEAAMX7EIQkCAEAAMX7WIQkIAEAAMTi8ZmDUBIAAMTi6ZmEJBgBAABB/9fF+xCMJPAAAADF81mLeBIAAMX7WYQkkAAAAMX7EQQkxfsQhCTgAAAAxftYhCT4AAAAxOLxmYMoEwAAxfsQjCQoAQAAxfsQVCQIxOLpqYwkiAAAAMTi+bmMJAABAADF+SjBQf/XxfsQDCTE4vGZhCSAAAAAxfsQTCQYxOLxqYQk6AAAAMX7EFQkIMTi6ZlDBMX7EFQkeMX7WcJBjYQk9AEAACX/AQAAQY2MJPUBAACB4f8BAADF81hMw1BBjYQk9gEAACX/AQAAxfNYTMtQQY2MJPcBAACB4f8BAADF81hMw1BBjYQk+AEAACX/AQAAxfNYTMtQQY2MJPkBAACB4f8BAADF81hMw1BBjYQk+gEAACX/AQAAxfNYTMtQQY2MJPsBAACB4f8BAADF81hMw1BBjYQk/AEAACX/AQAAxfNYTMtQQY2MJP0BAACB4f8BAADF81hMw1BBjYQk/gEAACX/AQAAxfNYTMtQQY1MJP+B4f8BAADF81hMw1BBjYQk2AEAACX/AQAAxfNYTMtQQY2MJNkBAACB4f8BAADF81hMw1BBjYQk2gEAACX/AQAAxfNYTMtQQY2MJNsBAACB4f8BAADF81hMw1BBjYQk3AEAACX/AQAAxfNYTMtQQY2MJN0BAACB4f8BAADF81hMw1BBjYQk3gEAACX/AQAAxfNYTMtQQY2MJN8BAACB4f8BAADF81hMw1BBjYQk4AEAACX/AQAAxfNYTMtQQY2MJOEBAACB4f8BAADF81hMw1BBjYQk4gEAACX/AQAAxfNYTMtQQY2MJOMBAACB4f8BAADF81hMw1BBjYQk5AEAACX/AQAAxfNYTMtQQY2MJOUBAACB4f8BAADF81hMw1BBjYQk5gEAACX/AQAAxfNYTMtQQY2MJOcBAACB4f8BAADF81hMw1BBjYQk6AEAACX/AQAAxfNYTMtQQY2MJOkBAACB4f8BAADF81hMw1BBjYQk6gEAACX/AQAAxfNYTMtQQY2MJOsBAACB4f8BAADF81hMw1BBjYQk7AEAACX/AQAAxfNYTMtQQY2MJO0BAACB4f8BAADF81hMw1BBjYQk7gEAACX/AQAAxfNYTMtQQY2MJO8BAACB4f8BAADF81hMw1BBjYQk8AEAACX/AQAAxfNYTMtQQY2MJPEBAACB4f8BAADF81hMw1BBjYQk8gEAACX/AQAAxfNYTMtQQY2MJPMBAACB4f8BAADF81hMw1BBjYQkoQAAACX/AQAAxfNYTMtQQY2MJKIAAACB4f8BAADF81hMw1BBjYQkowAAACX/AQAAxfNYTMtQQY2MJKQAAACB4f8BAADF81hMw1BBjYQkpQAAACX/AQAAxfNYTMtQQY2MJKYAAACB4f8BAADF81hMw1BBjYQkpwAAACX/AQAAxfNYTMtQQY2MJKgAAACB4f8BAADF81hMw1BBjYQkqQAAACX/AQAAxfNYTMtQQY2MJKoAAACB4f8BAADF81hMw1BBjYQkqwAAACX/AQAAxfNYTMtQQY2MJKwAAACB4f8BAADF81hMw1BBjYQkrQAAACX/AQAAxfNYTMtQQY2MJK4AAACB4f8BAADF81hMw1BBjYQkrwAAACX/AQAAxfNYTMtQQY2MJLAAAACB4f8BAADF81hMw1BBjYQksQAAACX/AQAAxfNYTMtQQY2MJLIAAACB4f8BAADF81hMw1BBjYQkswAAACX/AQAAxfNYTMtQQY2MJLQAAACB4f8BAADF81hMw1BBjYQktQAAACX/AQAAxfNYTMtQQY2MJLYAAACB4f8BAADF81hMw1BBjYQktwAAACX/AQAAxfNYTMtQQY2MJLgAAACB4f8BAADF81hMw1BBjYQkuQAAACX/AQAAxfNYTMtQQY2MJLoAAACB4f8BAADF81hMw1BBjYQkuwAAACX/AQAAxfNYTMtQQY2MJLwAAACB4f8BAADF81hMw1BBjYQkhQAAACX/AQAAxfNYTMtQQY2MJIYAAACB4f8BAADF81hMw1BBjYQkhwAAACX/AQAAxfNYTMtQQY2MJIgAAACB4f8BAADF81hMw1BBjYQkiQAAACX/AQAAxfNYTMtQQY2MJIoAAACB4f8BAADF81hMw1BBjYQkiwAAACX/AQAAxfNYTMtQQY2MJIwAAACB4f8BAADF81hMw1BBjYQkjQAAACX/AQAAxfNYTMtQQY2MJI4AAACB4f8BAADF81hMw1BBjYQkjwAAACX/AQAAxfNYTMtQQY2MJJAAAACB4f8BAADF81hMw1BBjYQkkQAAACX/AQAAxfNYTMtQQY2MJJIAAACB4f8BAADF81hMw1BBjYQkkwAAACX/AQAAxfNYTMtQQY2MJJQAAACB4f8BAADF81hMw1BBjYQklQAAACX/AQAAxfNYTMtQQY2MJJYAAACB4f8BAADF81hMw1BBjYQklwAAACX/AQAAxfNYTMtQQY2MJJgAAACB4f8BAADF81hMw1BBjYQkmQAAACX/AQAAxfNYTMtQQY2MJJoAAACB4f8BAADF81hMw1BBjYQkmwAAACX/AQAAxfNYTMtQQY2MJJwAAACB4f8BAADF81hMw1BBjYQknQAAACX/AQAAxfNYTMtQQY2MJJ4AAACB4f8BAADF81hMw1BBjYQknwAAACX/AQAAxfNYTMtQQY2MJKAAAACB4f8BAADF81hMw1BBjYQk2QAAACX/AQAAxfNYTMtQQY2MJNoAAACB4f8BAADF81hMw1BBjYQk2wAAACX/AQAAxfNYTMtQQY2MJNwAAACB4f8BAADF81hMw1BBjYQk3QAAACX/AQAAxfNYTMtQQY2MJN4AAACB4f8BAADF81hMw1BBjYQk3wAAACX/AQAAxfNYTMtQQY2MJOAAAACB4f8BAADF81hMw1BBjYQk4QAAACX/AQAAxfNYTMtQQY2MJOIAAACB4f8BAADF81hMw1BBjYQk4wAAACX/AQAAxfNYTMtQQY2MJOQAAACB4f8BAADF81hMw1BBjYQk5QAAACX/AQAAxfNYTMtQQY2MJOYAAACB4f8BAADF81hMw1BBjYQk5wAAACX/AQAAxfNYTMtQQY2MJOgAAACB4f8BAADF81hMw1BBjYQk6QAAACX/AQAAxfNYTMtQQY2MJOoAAACB4f8BAADF81hMw1BBjYQk6wAAACX/AQAAxfNYTMtQQY2MJOwAAACB4f8BAADF81hMw1BBjYQk7QAAACX/AQAAxfNYTMtQQY2MJO4AAACB4f8BAADF81hMw1BBjYQk7wAAACX/AQAAxfNYTMtQQY2MJPAAAACB4f8BAADF81hMw1BBjYQk8QAAACX/AQAAxfNYTMtQQY2MJPIAAACB4f8BAADF81hMw1BBjYQk8wAAACX/AQAAxfNYTMtQQY2MJPQAAACB4f8BAADF81hMw1BBjYQk9QAAACX/AQAAxfNYTMtQQY2MJL0AAACB4f8BAADF81hMw1BBjYQkvgAAACX/AQAAxfNYTMtQQY2MJL8AAACB4f8BAADF81hMw1BBjYQkwAAAACX/AQAAxfNYTMtQQY2MJMEAAACB4f8BAADF81hMw1BBjYQkwgAAACX/AQAAxfNYTMtQQY2MJMMAAACB4f8BAADF81hMw1BBjYQkxAAAACX/AQAAxfNYTMtQQY2MJMUAAACB4f8BAADF81hMw1BBjYQkxgAAACX/AQAAxfNYTMtQQY2MJMcAAACB4f8BAADF81hMw1BBjYQkyAAAACX/AQAAxfNYTMtQQY2MJMkAAACB4f8BAADF81hMw1BBjYQkygAAACX/AQAAxfNYTMtQQY2MJMsAAACB4f8BAADF81hMw1BBjYQkzAAAACX/AQAAxfNYTMtQQY2MJM0AAACB4f8BAADF81hMw1BBjYQkzgAAACX/AQAAxfNYTMtQQY2MJM8AAACB4f8BAADF81hMw1BBjYQk0AAAACX/AQAAxfNYTMtQQY2MJNEAAACB4f8BAADF81hMw1BBjYQk0gAAACX/AQAAxfNYTMtQQY2MJNMAAACB4f8BAADF81hMw1BBjYQk1AAAACX/AQAAxfNYTMtQQY2MJNUAAACB4f8BAADF81hMw1BBjYQk1gAAACX/AQAAxfNYTMtQQY2MJNcAAACB4f8BAADF81hMw1BBjYQk2AAAACX/AQAAxfNYTMtQQY1MJDCB4f8BAADF81hMw1BBjUQkMSX/AQAAxfNYTMtQQY1MJDKB4f8BAADF81hMw1BBjUQkMyX/AQAAxfNYTMtQQY1MJDSB4f8BAADF81hMw1BBjUQkNSX/AQAAxfNYTMtQQY1MJDaB4f8BAADF81hMw1BBjUQkNyX/AQAAxfNYTMtQQY1MJDiB4f8BAADF81hMw1BBjUQkOSX/AQAAxfNYTMtQQY1MJDqB4f8BAADF81hMw1BBjUQkOyX/AQAAxfNYTMtQQY1MJDyB4f8BAADF81hMw1BBjUQkPSX/AQAAxfNYTMtQQY1MJD6B4f8BAADF81hMw1BBjUQkPyX/AQAAxfNYTMtQQY1MJECB4f8BAADF81hMw1BBjUQkQSX/AQAAxfNYTMtQQY1MJEKB4f8BAADF81hMw1BBjUQkQyX/AQAAxfNYTMtQQY1MJESB4f8BAADF81hMw1BBjUQkRSX/AQAAxfNYTMtQQY1MJEaB4f8BAADF81hMw1BBjUQkRyX/AQAAxfNYTMtQQY1MJEiB4f8BAADF81hMw1BBjUQkSSX/AQAAxfNYTMtQQY1MJEqB4f8BAADF81hMw1BBjUQkSyX/AQAAxfNYTMtQQY1MJBSB4f8BAADF81hMw1BBjUQkFSX/AQAAxfNYTMtQQY1MJBaB4f8BAADF81hMw1BBjUQkFyX/AQAAxfNYTMtQQY1MJBiB4f8BAADF81hMw1BBjUQkGSX/AQAAxfNYTMtQQY1MJBqB4f8BAADF81hMw1BBjUQkGyX/AQAAxfNYTMtQQY1MJByB4f8BAADF81hMw1BBjUQkHSX/AQAAxfNYTMtQQY1MJB6B4f8BAADF81hMw1BBjUQkHyX/AQAAxfNYTMtQQY1MJCCB4f8BAADF81hMw1BBjUQkISX/AQAAxfNYTMtQQY1MJCKB4f8BAADF81hMw1BBjUQkIyX/AQAAxfNYTMtQQY1MJCSB4f8BAADF81hMw1BBjUQkJSX/AQAAxfNYTMtQQY1MJCaB4f8BAADF81hMw1BBjUQkJyX/AQAAxfNYTMtQQY1MJCiB4f8BAADF81hMw1BBjUQkKSX/AQAAxfNYTMtQQY1MJCqB4f8BAADF81hMw1BBjUQkKyX/AQAAxfNYTMtQQY1MJCyB4f8BAADF81hMw1BBjUQkLSX/AQAAxfNYTMtQQY1MJC6B4f8BAADF81hMw1BBjUQkLyX/AQAAxfNYTMtQQY1MJGiB4f8BAADF81hMw1BBjUQkaSX/AQAAxfNYTMtQQY1MJGqB4f8BAADF81hMw1BBjUQkayX/AQAAxfNYTMtQQY1MJGyB4f8BAADF81hMw1BBjUQkbSX/AQAAxfNYTMtQQY1MJG6B4f8BAADF81hMw1BBjUQkbyX/AQAAxfNYTMtQQY1MJHCB4f8BAADF81hMw1BBjUQkcSX/AQAAxfNYTMtQQY1MJHKB4f8BAADF81hMw1BBjUQkcyX/AQAAxfNYTMtQQY1MJHSB4f8BAADF81hMw1BBjUQkdSX/AQAAxfNYTMtQQY1MJHaB4f8BAADF81hMw1BBjUQkdyX/AQAAxfNYTMtQQY1MJHiB4f8BAADF81hMw1BBjUQkeSX/AQAAxfNYTMtQQY1MJHqB4f8BAADF81hMw1BBjUQkeyX/AQAAxfNYTMtQQY1MJHyB4f8BAADF81hMw1BBjUQkfSX/AQAAxfNYTMtQQY1MJH6B4f8BAADF81hMw1BBjUQkfyX/AQAAxfNYTMtQQY2MJIAAAACB4f8BAADF81hMw1BBjYQkgQAAACX/AQAAxfNYTMtQQY2MJIIAAACB4f8BAADF81hMw1BBjYQkgwAAACX/AQAAxfNYTMtQQY2MJIQAAACB4f8BAADF81hMw1BBjUQkTCX/AQAAxfNYTMtQQY1MJE2B4f8BAADF81hMw1BBjUQkTiX/AQAAxfNYTMtQQY1MJE+B4f8BAADF81hMw1BBjUQkUCX/AQAAxfNYTMtQQY1MJFGB4f8BAADF81hMw1BBjUQkUiX/AQAAxfNYTMtQQY1MJFOB4f8BAADF81hMw1BBjUQkVCX/AQAAxfNYTMtQQY1MJFWB4f8BAADF81hMw1BBjUQkViX/AQAAxfNYTMtQQY1MJFeB4f8BAADF81hMw1BBjUQkWCX/AQAAxfNYTMtQQY1MJFmB4f8BAADF81hMw1BBjUQkWiX/AQAAxfNYTMtQQY1MJFuB4f8BAADF81hMw1BBjUQkXCX/AQAAxfNYTMtQQY1MJF2B4f8BAADF81hMw1BBjUQkXiX/AQAAxfNYTMtQQY1MJF+B4f8BAADF81hMw1BBjUQkYCX/AQAAxfNYTMtQQY1MJGGB4f8BAADF81hMw1BBjUQkYiX/AQAAxfNYTMtQQY1MJGOB4f8BAADF81hMw1BBjUQkZCX/AQAAxfNYTMtQQY1MJGWB4f8BAADF81hMw1BBjUQkZiX/AQAAxfNYTMtQQY1MJGeB4f8BAADF81hMw1BBjYQkgwEAACX/AQAAxfNYTMtQQY2MJIQBAACB4f8BAADF81hMw1BBjYQkhQEAACX/AQAAxfNYTMtQQY2MJIYBAACB4f8BAADF81hMw1BBjYQkhwEAACX/AQAAxfNYTMtQQY2MJIgBAACB4f8BAADF81hMw1BBjYQkiQEAACX/AQAAxfNYTMtQQY2MJIoBAACB4f8BAADF81hMw1BBjYQkiwEAACX/AQAAxfNYTMtQQY2MJIwBAACB4f8BAADF81hMw1BBjYQkjQEAACX/AQAAxfNYTMtQQY2MJI4BAACB4f8BAADF81hMw1BBjYQkjwEAACX/AQAAxfNYTMtQQY2MJJABAACB4f8BAADF81hMw1BBjYQkkQEAACX/AQAAxfNYTMtQQY2MJJIBAACB4f8BAADF81hMw1BBjYQkkwEAACX/AQAAxfNYTMtQQY2MJJQBAACB4f8BAADF81hMw1BBjYQklQEAACX/AQAAxfNYTMtQQY2MJJYBAACB4f8BAADF81hMw1BBjYQklwEAACX/AQAAxfNYTMtQQY2MJJgBAACB4f8BAADF81hMw1BBjYQkmQEAACX/AQAAxfNYTMtQQY2MJJoBAACB4f8BAADF81hMw1BBjYQkmwEAACX/AQAAxfNYTMtQQY2MJJwBAACB4f8BAADF81hMw1BBjYQknQEAACX/AQAAxfNYTMtQQY2MJJ4BAACB4f8BAADF81hMw1BBjYQkZwEAACX/AQAAxfNYTMtQQY2MJGgBAACB4f8BAADF81hMw1BBjYQkaQEAACX/AQAAxfNYTMtQQY2MJGoBAACB4f8BAADF81hMw1BBjYQkawEAACX/AQAAxfNYTMtQQY2MJGwBAACB4f8BAADF81hMw1BBjYQkbQEAACX/AQAAxfNYTMtQQY2MJG4BAACB4f8BAADF81hMw1BBjYQkbwEAACX/AQAAxfNYTMtQQY2MJHABAACB4f8BAADF81hMw1BBjYQkcQEAACX/AQAAxfNYTMtQQY2MJHIBAACB4f8BAADF81hMw1BBjYQkcwEAACX/AQAAxfNYTMtQQY2MJHQBAACB4f8BAADF81hMw1BBjYQkdQEAACX/AQAAxfNYTMtQQY2MJHYBAACB4f8BAADF81hMw1BBjYQkdwEAACX/AQAAxfNYTMtQQY2MJHgBAACB4f8BAADF81hMw1BBjYQkeQEAACX/AQAAxfNYTMtQQY2MJHoBAACB4f8BAADF81hMw1BBjYQkewEAACX/AQAAxfNYTMtQQY2MJHwBAACB4f8BAADF81hMw1BBjYQkfQEAACX/AQAAxfNYTMtQQY2MJH4BAACB4f8BAADF81hMw1BBjYQkfwEAACX/AQAAxfNYTMtQQY2MJIABAACB4f8BAADF81hMw1BBjYQkgQEAACX/AQAAxfNYTMtQQY2MJIIBAACB4f8BAADF81hMw1BBjYQkuwEAACX/AQAAxfNYTMtQQY2MJLwBAACB4f8BAADF81hMw1BBjYQkvQEAACX/AQAAxfNYTMtQQY2MJL4BAACB4f8BAADF81hMw1BBjYQkvwEAACX/AQAAxfNYTMtQQY2MJMABAACB4f8BAADF81hMw1BBjYQkwQEAACX/AQAAxfNYTMtQQY2MJMIBAACB4f8BAADF81hMw1BBjYQkwwEAACX/AQAAxfNYTMtQQY2MJMQBAACB4f8BAADF81hMw1BBjYQkxQEAACX/AQAAxfNYTMtQQY2MJMYBAACB4f8BAADF81hMw1BBjYQkxwEAACX/AQAAxfNYTMtQQY2MJMgBAACB4f8BAADF81hMw1BBjYQkyQEAACX/AQAAxfNYTMtQQY2MJMoBAACB4f8BAADF81hMw1BBjYQkywEAACX/AQAAxfNYTMtQQY2MJMwBAACB4f8BAADF81hMw1BBjYQkzQEAACX/AQAAxfNYTMtQQY2MJM4BAACB4f8BAADF81hMw1BBjYQkzwEAACX/AQAAxfNYTMtQQY2MJNABAACB4f8BAADF81hMw1BBjYQk0QEAACX/AQAAxfNYTMtQQY2MJNIBAACB4f8BAADF81hMw1BBjYQk0wEAACX/AQAAxfNYTMtQQY2MJNQBAACB4f8BAADF81hMw1BBjYQk1QEAACX/AQAAxfNYTMtQQY2MJNYBAACB4f8BAADF81hMw1BBjYQk1wEAACX/AQAAxfNYTMtQQY2MJJ8BAACB4f8BAADF81hMw1BBjYQkoAEAACX/AQAAxfNYTMtQQY2MJKEBAACB4f8BAADF81hMw1BBjYQkogEAACX/AQAAxfNYTMtQQY2MJKMBAACB4f8BAADF81hMw1BBjYQkpAEAACX/AQAAxfNYTMtQQY2MJKUBAACB4f8BAADF81hMw1BBjYQkpgEAACX/AQAAxfNYTMtQQY2MJKcBAACB4f8BAADF81hMw1BBjYQkqAEAACX/AQAAxfNYTMtQQY2MJKkBAACB4f8BAADF81hMw1BBjYQkqgEAACX/AQAAxfNYTMtQQY2MJKsBAACB4f8BAADF81hMw1BBjYQkrAEAACX/AQAAxfNYTMtQQY2MJK0BAACB4f8BAADF81hMw1BBjYQkrgEAACX/AQAAxfNYTMtQQY2MJK8BAACB4f8BAADF81hMw1BBjYQksAEAACX/AQAAxfNYTMtQQY2MJLEBAACB4f8BAADF81hMw1BBjYQksgEAACX/AQAAxfNYTMtQQY2MJLMBAACB4f8BAADF81hMw1BBjYQktAEAACX/AQAAxfNYTMtQQY2MJLUBAACB4f8BAADF81hMw1BBjYQktgEAACX/AQAAxfNYTMtQQY2MJLcBAACB4f8BAADF81hMw1BBjYQkuAEAACX/AQAAxfNYTMtQQY2MJLkBAACB4f8BAADF81hMw1BBjYQkugEAACX/AQAAxfNYTMtQQY2MJBIBAACB4f8BAADF81hMw1BBjYQkEwEAACX/AQAAxfNYTMtQQY2MJBQBAACB4f8BAADF81hMw1BBjYQkFQEAACX/AQAAxfNYTMtQQY2MJBYBAACB4f8BAADF81hMw1BBjYQkFwEAACX/AQAAxfNYTMtQQY2MJBgBAACB4f8BAADF81hMw1BBjYQkGQEAACX/AQAAxfNYTMtQQY2MJBoBAACB4f8BAADF81hMw1BBjYQkGwEAACX/AQAAxfNYTMtQQY2MJBwBAACB4f8BAADF81hMw1BBjYQkHQEAACX/AQAAxfNYTMtQQY2MJB4BAACB4f8BAADF81hMw1BBjYQkHwEAACX/AQAAxfNYTMtQQY2MJCABAACB4f8BAADF81hMw1BBjYQkIQEAACX/AQAAxfNYTMtQQY2MJCIBAACB4f8BAADF81hMw1BBjYQkIwEAACX/AQAAxfNYTMtQQY2MJCQBAACB4f8BAADF81hMw1BBjYQkJQEAACX/AQAAxfNYTMtQQY2MJCYBAACB4f8BAADF81hMw1BBjYQkJwEAACX/AQAAxfNYTMtQQY2MJCgBAACB4f8BAADF81hMw1BBjYQkKQEAACX/AQAAxfNYTMtQQY2MJCoBAACB4f8BAADF81hMw1BBjYQkKwEAACX/AQAAxfNYTMtQQY2MJCwBAACB4f8BAADF81hMw1BBjYQkLQEAACX/AQAAxfNYTMtQQY2MJPYAAACB4f8BAADF81hMw1BBjYQk9wAAACX/AQAAxfNYTMtQQY2MJPgAAACB4f8BAADF81hMw1BBjYQk+QAAACX/AQAAxfNYTMtQQY2MJPoAAACB4f8BAADF81hMw1BBjYQk+wAAACX/AQAAxfNYTMtQQY2MJPwAAACB4f8BAADF81hMw1BBjYQk/QAAACX/AQAAxfNYTMtQQY2MJP4AAACB4f8BAADF81hMw1BBjYQk/wAAACX/AQAAxfNYTMtQQY2MJAABAACB4f8BAADF81hMw1BBjYQkAQEAACX/AQAAxfNYTMtQQY2MJAIBAACB4f8BAADF81hMw1BBjYQkAwEAACX/AQAAxfNYTMtQQY2MJAQBAACB4f8BAADF81hMw1BBjYQkBQEAACX/AQAAxfNYTMtQQY2MJAYBAACB4f8BAADF81hMw1BBjYQkBwEAACX/AQAAxfNYTMtQQY2MJAgBAACB4f8BAADF81hMw1BBjYQkCQEAACX/AQAAxfNYTMtQQY2MJAoBAACB4f8BAADF81hMw1BBjYQkCwEAACX/AQAAxfNYTMtQQY2MJAwBAACB4f8BAADF81hMw1BBjYQkDQEAACX/AQAAxfNYTMtQQY2MJA4BAACB4f8BAADF81hMw1BBjYQkDwEAACX/AQAAxfNYTMtQQY2MJBABAACB4f8BAADF81hMw1BBjYQkEQEAACX/AQAAxfNYTMtQQY2MJEoBAACB4f8BAADF81hMw1BBjYQkSwEAACX/AQAAxfNYTMtQQY2MJEwBAACB4f8BAADF81hMw1BBjYQkTQEAACX/AQAAxfNYTMtQQY2MJE4BAACB4f8BAADF81hMw1BBjYQkTwEAACX/AQAAxfNYTMtQQY2MJFABAACB4f8BAADF81hMw1BBjYQkUQEAACX/AQAAxfNYTMtQQY2MJFIBAACB4f8BAADF81hMw1BBjYQkUwEAACX/AQAAxfNYTMtQQY2MJFQBAACB4f8BAADF81hMw1BBjYQkVQEAACX/AQAAxfNYTMtQQY2MJFYBAACB4f8BAADF81hMw1BBjYQkVwEAACX/AQAAxfNYTMtQQY2MJFgBAACB4f8BAADF81hMw1BBjYQkWQEAACX/AQAAxfNYTMtQQY2MJFoBAACB4f8BAADF81hMw1BBjYQkWwEAACX/AQAAxfNYTMtQQY2MJFwBAACB4f8BAADF81hMw1BBjYQkXQEAACX/AQAAxfNYTMtQQY2MJF4BAACB4f8BAADF81hMw1BBjYQkXwEAACX/AQAAxfNYTMtQQY2MJGABAACB4f8BAADF81hMw1BBjYQkYQEAACX/AQAAxfNYTMtQQY2MJGIBAACB4f8BAADF81hMw1BBjYQkYwEAACX/AQAAxfNYTMtQQY2MJGQBAACB4f8BAADF81hMw1BBjYQkZQEAACX/AQAAxfNYTMtQQY2MJGYBAACB4f8BAADF81hMw1BBjYQkLgEAACX/AQAAxfNYTMtQQY2MJC8BAACB4f8BAADF81hMw1BBjYQkMAEAACX/AQAAxfNYTMtQQY2MJDEBAACB4f8BAADF81hMw1BBjYQkMgEAACX/AQAAxfNYTMtQQY2MJDMBAACB4f8BAADF81hMw1BBjYQkNAEAACX/AQAAxfNYTMtQQY2MJDUBAACB4f8BAADF81hMw1BBjYQkNgEAACX/AQAAxfNYTMtQQY2MJDcBAACB4f8BAADF81hMw1BBjYQkOAEAACX/AQAAxfNYTMtQQY2MJDkBAACB4f8BAADF81hMw1BBjYQkOgEAACX/AQAAxfNYTMtQQY2MJDsBAACB4f8BAADF81hMw1BBjYQkPAEAACX/AQAAxfNYTMtQQY2MJD0BAACB4f8BAADF81hMw1BBjYQkPgEAACX/AQAAxfNYTMtQQY2MJD8BAACB4f8BAADF81hMw1BBjYQkQAEAACX/AQAAxfNYTMtQQY2MJEEBAACB4f8BAADF81hMw1BBjYQkQgEAACX/AQAAxfNYTMtQQY2MJEMBAACB4f8BAADF81hMw1BBjYQkRAEAACX/AQAAxfNYTMtQQY2MJEUBAACB4f8BAADF81hMw1BBjYQkRgEAACX/AQAAxfNYTMtQQY2MJEcBAACB4f8BAADF81hMw1BBjYQkSAEAACX/AQAAxfNYTMtQQY2MJEkBAACB4f8BAADF81hMw1BBjUQkDSX/AQAAxfNYTMtQQY1MJA6B4f8BAADF81hMw1BBjUQkDyX/AQAAxfNYTMtQQY1MJBCB4f8BAADF81hMw1BBjUQkESX/AQAAxfNYTMtQQY1MJBOB4f8BAADF81hMw1BBjUQkEiX/AQAAxfNYTMtQxfNYTMNQxOL5mYswEwAARIngJf8/AADF+xGMwzgTAABEieArRCQUJf8/AADF+xBEJHDE4vm5jMM4EwAAxfNZRCRoxfsswInBwfkfxOJw8sA9UMMAALlQwwAAD0PB99BEAeAPt8DF+xBEJEDF+1mEw3gTAgDF+SlEJCDF+VSEJDABAADF+xCLYBMCADHAxfkuwQ+XwMXzXMjE4vmZjMNIEwIAxfsRi1gTAgDF819EJGDF61mLQBMCAMX7EQwkSLgAAAAAAAAAAP/QxfsQTCRQxOLxmUQkWMXxV8nF+1/BxftZBCTF+xCLcBMCAMTi+ZuLOBMCAMX7EYtoEwIAD7drHMXzWUQkSEi4AAAAAAAAAAD/0EiLhCTYAAAAxfkoTCQgxKLxqQTwxfsRhOt4EwIAxfsQSwzF+xCTmBMKAMXrWZt4EwoAxfsQo5ATCgDE4tm5m4ATCgDE4vGt2MTi2blUJDDF+xGbiBMKAMXrWMPF+1nBSIuEJNAAAADEoXsRBPBIi4QkyAAAAMShexEE8ESLYxxB/8REiWMci4NQEAAAiYNUEAAAxfkQs2gQAADF+xCjcBAAAMX5EbNwEAAAxXsQq4gQAADFexGrkBAAAMX7EJOYEAAAxfsRk6AQAADF+xCDsBAAAMX7EYO4EAAAxfkQuwARAADFexCbCBEAAMX5EbsIEQAAxfkQqzARAADFexCTOBEAAMX5Eas4EQAAxXkQi2ARAADFexCDaBEAAMV5EYtoEQAAxXsQs4gRAADFexGzkBEAAMX4EIvYEQAAxfgRi+ARAADF+BCLCBIAAMX4EYsQEgAAxfgQizgSAADF+BGLQBIAAMX7EItgEgAAxfsRi2gSAADF+BCLsBIAAMX4EYu4EgAAxfgQi+ASAADF+BGL6BIAAMX4EIsQEwAAxfgRixgTAADF+xCLWBMCAMX7EYtgEwIAxfsQi2gTAgDF+xGLcBMCAMX4EIuIEwoAxfgRi5ATCgBJ/8ZNOfUPhZHT//9IgcRIAQAAW0FcQV1BXkFfXcMAAAAAAAAAAAAAAAAA8D8AAAAAAHAHQYhBQYLJedVAzDt/Zp6g9j9SkSrkKn1rQAEgPBV6Ueo/x3GUSzOv6T92pV1dqZj2P67K9TTZSJQ/b8OUPZKV8j87OUNxcyq5PMdxlEszr+m/AAAAAAAAAMBvw5Q9kpUCQAAAAAAAADpAO0PVWYyic0A/wfVySo7FP33jzI8XHPE/0/7Zmzlm4D/XtOLSYBHmPwQyLiGnfB5AfgECFocJ6T8IkvBPtmXPP34BAhaHCem/t3wo3uI2Gj8IkvBPtmXfPy6keqhYZEw/0/7Zmzlm4L/XtOLSYBH2PwQyLiGnfC5AP8H1ckqOxb9948yPFxwBQMq89qigxEpAAAAAAAAAFEBSkSrkKn1bQAAAAAAAAARAXjhVKXpqT0CN7bWg98bAPgAAAAAAiKPAzDt/Zp6g9r+amZmZmZkhQAAAAAAAAKlAAAAoAAAAJD4AADgAAAAsPgAAKAAAAEQ+GC1EVPshGUAYLURU+yH5P2EyVTAqqSM/GC1EVPshCcBJr7ya8td6PhgtRFT7Iem/VOQQcXMqqT4AAAAAAADoPx6n6Egu/+8/AAAAAAAA4D8AAAAAAAAQAAAAAAAAADRAAAAAAAAAGEBbHC6hpULFPwAAAAAAAABAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAAAAAAAAAAB2pV1dqZgGQAAAAAAAAAAAAAAAAAAA8D8AAAAAAAAAAMq89qigxFpALqR6qFhkPD8IkvBPtmXPPwAAAAAAAADAAAAAAACIk8D/////////f/////////9/eyJuYW1lIjogImZhdXN0Z2VuLTgiLCJmaWxlbmFtZSI6ICJmYXVzdGdlbi04IiwidmVyc2lvbiI6ICIyLjUwLjYiLCJjb21waWxlX29wdGlvbnMiOiAiLWxhbmcgbGx2bSAxNC4wLjYgLWVzIDEgLW1jZCAxNiAtZG91YmxlIC1mdHogMCIsImxpYnJhcnlfbGlzdCI6IFsiL1VzZXJzL2dyZWcvRG9jdW1lbnRzL01heCA4L1BhY2thZ2VzL2ZhdXN0Z2VuL2V4dGVybmFscy9tc3AvZmF1c3RnZW5+Lm14by9Db250ZW50cy9SZXNvdXJjZXMvc3RkZmF1c3QubGliIiwiL1VzZXJzL2dyZWcvRG9jdW1lbnRzL01heCA4L1BhY2thZ2VzL2ZhdXN0Z2VuL2V4dGVybmFscy9tc3AvZmF1c3RnZW5+Lm14by9Db250ZW50cy9SZXNvdXJjZXMvY29tcHJlc3NvcnMubGliIiwiL1VzZXJzL2dyZWcvRG9jdW1lbnRzL01heCA4L1BhY2thZ2VzL2ZhdXN0Z2VuL2V4dGVybmFscy9tc3AvZmF1c3RnZW5+Lm14by9Db250ZW50cy9SZXNvdXJjZXMvb3NjaWxsYXRvcnMubGliIiwiL1VzZXJzL2dyZWcvRG9jdW1lbnRzL01heCA4L1BhY2thZ2VzL2ZhdXN0Z2VuL2V4dGVybmFscy9tc3AvZmF1c3RnZW5+Lm14by9Db250ZW50cy9SZXNvdXJjZXMvbWF0aHMubGliIiwiL1VzZXJzL2dyZWcvRG9jdW1lbnRzL01heCA4L1BhY2thZ2VzL2ZhdXN0Z2VuL2V4dGVybmFscy9tc3AvZmF1c3RnZW5+Lm14by9Db250ZW50cy9SZXNvdXJjZXMvcGxhdGZvcm0ubGliIiwiL1VzZXJzL2dyZWcvRG9jdW1lbnRzL01heCA4L1BhY2thZ2VzL2ZhdXN0Z2VuL2V4dGVybmFscy9tc3AvZmF1c3RnZW5+Lm14by9Db250ZW50cy9SZXNvdXJjZXMvbm9pc2VzLmxpYiIsIi9Vc2Vycy9ncmVnL0RvY3VtZW50cy9NYXggOC9QYWNrYWdlcy9mYXVzdGdlbi9leHRlcm5hbHMvbXNwL2ZhdXN0Z2Vufi5teG8vQ29udGVudHMvUmVzb3VyY2VzL2ZpbHRlcnMubGliIiwiL1VzZXJzL2dyZWcvRG9jdW1lbnRzL01heCA4L1BhY2thZ2VzL2ZhdXN0Z2VuL2V4dGVybmFscy9tc3AvZmF1c3RnZW5+Lm14by9Db250ZW50cy9SZXNvdXJjZXMvYW5hbHl6ZXJzLmxpYiIsIi9Vc2Vycy9ncmVnL0RvY3VtZW50cy9NYXggOC9QYWNrYWdlcy9mYXVzdGdlbi9leHRlcm5hbHMvbXNwL2ZhdXN0Z2Vufi5teG8vQ29udGVudHMvUmVzb3VyY2VzL3NpZ25hbHMubGliIiwiL1VzZXJzL2dyZWcvRG9jdW1lbnRzL01heCA4L1BhY2thZ2VzL2ZhdXN0Z2VuL2V4dGVybmFscy9tc3AvZmF1c3RnZW5+Lm14by9Db250ZW50cy9SZXNvdXJjZXMvYmFzaWNzLmxpYiJdLCJpbmNsdWRlX3BhdGhuYW1lcyI6IFsiL1VzZXJzL2dyZWcvRG9jdW1lbnRzL01heCA4L1BhY2thZ2VzL2ZhdXN0Z2VuL2V4dGVybmFscy9tc3AvZmF1c3RnZW5+Lm14by9Db250ZW50cy9SZXNvdXJjZXMiLCIvc2hhcmUvZmF1c3QiLCIvdXNyL2xvY2FsL3NoYXJlL2ZhdXN0IiwiL3Vzci9zaGFyZS9mYXVzdCIsIi4iXSwic2l6ZSI6IDY2MDM4NCwiaW5wdXRzIjogMSwib3V0cHV0cyI6IDIsInNyX2luZGV4IjogMCwibWV0YSI6IFsgeyAiYW5hbHl6ZXJzLmxpYi9hbXBfZm9sbG93ZXJfYXI6YXV0aG9yIjogIkpvbmF0YW4gTGlsamVkYWhsLCByZXZpc2VkIGJ5IFJvbWFpbiBNaWNob24iIH0seyAiYW5hbHl6ZXJzLmxpYi9uYW1lIjogIkZhdXN0IEFuYWx5emVyIExpYnJhcnkiIH0seyAiYW5hbHl6ZXJzLmxpYi92ZXJzaW9uIjogIjAuMiIgfSx7ICJiYXNpY3MubGliL25hbWUiOiAiRmF1c3QgQmFzaWMgRWxlbWVudCBMaWJyYXJ5IiB9LHsgImJhc2ljcy5saWIvdmVyc2lvbiI6ICIwLjgiIH0seyAiY29tcGlsZV9vcHRpb25zIjogIi1sYW5nIGxsdm0gMTQuMC42IC1lcyAxIC1tY2QgMTYgLWRvdWJsZSAtZnR6IDAiIH0seyAiY29tcHJlc3NvcnMubGliL2NvbXByZXNzaW9uX2dhaW5fbW9ubzphdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJjb21wcmVzc29ycy5saWIvY29tcHJlc3Npb25fZ2Fpbl9tb25vOmNvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMTQtMjAyMCBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NfY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJjb21wcmVzc29ycy5saWIvY29tcHJlc3Npb25fZ2Fpbl9tb25vOmxpY2Vuc2UiOiAiTUlULXN0eWxlIFNUSy00LjMgbGljZW5zZSIgfSx7ICJjb21wcmVzc29ycy5saWIvY29tcHJlc3Nvcl9sYWRfbW9ubzphdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJjb21wcmVzc29ycy5saWIvY29tcHJlc3Nvcl9sYWRfbW9ubzpjb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDE0LTIwMjAgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zX2Njcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiY29tcHJlc3NvcnMubGliL2NvbXByZXNzb3JfbGFkX21vbm86bGljZW5zZSI6ICJNSVQtc3R5bGUgU1RLLTQuMyBsaWNlbnNlIiB9LHsgImNvbXByZXNzb3JzLmxpYi9jb21wcmVzc29yX21vbm86YXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiY29tcHJlc3NvcnMubGliL2NvbXByZXNzb3JfbW9ubzpjb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDE0LTIwMjAgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zX2Njcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiY29tcHJlc3NvcnMubGliL2NvbXByZXNzb3JfbW9ubzpsaWNlbnNlIjogIk1JVC1zdHlsZSBTVEstNC4zIGxpY2Vuc2UiIH0seyAiY29tcHJlc3NvcnMubGliL2xpbWl0ZXJfMTE3Nl9SNF9tb25vOmF1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImNvbXByZXNzb3JzLmxpYi9saW1pdGVyXzExNzZfUjRfbW9ubzpjb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDE0LTIwMjAgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zX2Njcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiY29tcHJlc3NvcnMubGliL2xpbWl0ZXJfMTE3Nl9SNF9tb25vOmxpY2Vuc2UiOiAiTUlULXN0eWxlIFNUSy00LjMgbGljZW5zZSIgfSx7ICJjb21wcmVzc29ycy5saWIvbmFtZSI6ICJGYXVzdCBDb21wcmVzc29yIEVmZmVjdCBMaWJyYXJ5IiB9LHsgImNvbXByZXNzb3JzLmxpYi92ZXJzaW9uIjogIjAuNCIgfSx7ICJmaWxlbmFtZSI6ICJmYXVzdGdlbi04IiB9LHsgImZpbHRlcnMubGliL2ZpcjphdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJmaWx0ZXJzLmxpYi9maXI6Y29weXJpZ2h0IjogIkNvcHlyaWdodCAoQykgMjAwMy0yMDE5IGJ5IEp1bGl1cyBPLiBTbWl0aCBJSUkgPGpvc19jY3JtYS5zdGFuZm9yZC5lZHU+IiB9LHsgImZpbHRlcnMubGliL2ZpcjpsaWNlbnNlIjogIk1JVC1zdHlsZSBTVEstNC4zIGxpY2Vuc2UiIH0seyAiZmlsdGVycy5saWIvaWlyOmF1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImZpbHRlcnMubGliL2lpcjpjb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zX2Njcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVycy5saWIvaWlyOmxpY2Vuc2UiOiAiTUlULXN0eWxlIFNUSy00LjMgbGljZW5zZSIgfSx7ICJmaWx0ZXJzLmxpYi9sb3dwYXNzMF9oaWdocGFzczEiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zX2Njcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVycy5saWIvbG93cGFzczBfaGlnaHBhc3MxOmF1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImZpbHRlcnMubGliL2xvd3Bhc3MzZTphdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJmaWx0ZXJzLmxpYi9sb3dwYXNzM2U6Y29weXJpZ2h0IjogIkNvcHlyaWdodCAoQykgMjAwMy0yMDE5IGJ5IEp1bGl1cyBPLiBTbWl0aCBJSUkgPGpvc19jY3JtYS5zdGFuZm9yZC5lZHU+IiB9LHsgImZpbHRlcnMubGliL2xvd3Bhc3MzZTpsaWNlbnNlIjogIk1JVC1zdHlsZSBTVEstNC4zIGxpY2Vuc2UiIH0seyAiZmlsdGVycy5saWIvbG93cGFzczZlOmF1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImZpbHRlcnMubGliL2xvd3Bhc3M2ZTpjb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zX2Njcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVycy5saWIvbG93cGFzczZlOmxpY2Vuc2UiOiAiTUlULXN0eWxlIFNUSy00LjMgbGljZW5zZSIgfSx7ICJmaWx0ZXJzLmxpYi9sb3dwYXNzOmF1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImZpbHRlcnMubGliL2xvd3Bhc3M6Y29weXJpZ2h0IjogIkNvcHlyaWdodCAoQykgMjAwMy0yMDE5IGJ5IEp1bGl1cyBPLiBTbWl0aCBJSUkgPGpvc19jY3JtYS5zdGFuZm9yZC5lZHU+IiB9LHsgImZpbHRlcnMubGliL2xvd3Bhc3M6bGljZW5zZSI6ICJNSVQtc3R5bGUgU1RLLTQuMyBsaWNlbnNlIiB9LHsgImZpbHRlcnMubGliL25hbWUiOiAiRmF1c3QgRmlsdGVycyBMaWJyYXJ5IiB9LHsgImZpbHRlcnMubGliL3RmMTphdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJmaWx0ZXJzLmxpYi90ZjE6Y29weXJpZ2h0IjogIkNvcHlyaWdodCAoQykgMjAwMy0yMDE5IGJ5IEp1bGl1cyBPLiBTbWl0aCBJSUkgPGpvc19jY3JtYS5zdGFuZm9yZC5lZHU+IiB9LHsgImZpbHRlcnMubGliL3RmMTpsaWNlbnNlIjogIk1JVC1zdHlsZSBTVEstNC4zIGxpY2Vuc2UiIH0seyAiZmlsdGVycy5saWIvdGYxczphdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJmaWx0ZXJzLmxpYi90ZjFzOmNvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMDMtMjAxOSBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NfY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJmaWx0ZXJzLmxpYi90ZjFzOmxpY2Vuc2UiOiAiTUlULXN0eWxlIFNUSy00LjMgbGljZW5zZSIgfSx7ICJmaWx0ZXJzLmxpYi90ZjI6YXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiZmlsdGVycy5saWIvdGYyOmNvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMDMtMjAxOSBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NfY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJmaWx0ZXJzLmxpYi90ZjI6bGljZW5zZSI6ICJNSVQtc3R5bGUgU1RLLTQuMyBsaWNlbnNlIiB9LHsgImZpbHRlcnMubGliL3RmMnM6YXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiZmlsdGVycy5saWIvdGYyczpjb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zX2Njcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVycy5saWIvdGYyczpsaWNlbnNlIjogIk1JVC1zdHlsZSBTVEstNC4zIGxpY2Vuc2UiIH0seyAiZmlsdGVycy5saWIvdmVyc2lvbiI6ICIwLjMiIH0seyAibWF0aHMubGliL2F1dGhvciI6ICJHUkFNRSIgfSx7ICJtYXRocy5saWIvY29weXJpZ2h0IjogIkdSQU1FIiB9LHsgIm1hdGhzLmxpYi9saWNlbnNlIjogIkxHUEwgd2l0aCBleGNlcHRpb24iIH0seyAibWF0aHMubGliL25hbWUiOiAiRmF1c3QgTWF0aCBMaWJyYXJ5IiB9LHsgIm1hdGhzLmxpYi92ZXJzaW9uIjogIjIuNSIgfSx7ICJuYW1lIjogImZhdXN0Z2VuLTgiIH0seyAibm9pc2VzLmxpYi9uYW1lIjogIkZhdXN0IE5vaXNlIEdlbmVyYXRvciBMaWJyYXJ5IiB9LHsgIm5vaXNlcy5saWIvdmVyc2lvbiI6ICIwLjQiIH0seyAib3NjaWxsYXRvcnMubGliL2xmX3Nhd3BvczphdXRob3IiOiAiQmFydCBCcm91bnMsIHJldmlzZWQgYnkgU3TDqXBoYW5lIExldHoiIH0seyAib3NjaWxsYXRvcnMubGliL2xmX3Nhd3BvczpsaWNlbmNlIjogIlNUSy00LjMiIH0seyAib3NjaWxsYXRvcnMubGliL25hbWUiOiAiRmF1c3QgT3NjaWxsYXRvciBMaWJyYXJ5IiB9LHsgIm9zY2lsbGF0b3JzLmxpYi9zYXcxOmF1dGhvciI6ICJCYXJ0IEJyb3VucyIgfSx7ICJvc2NpbGxhdG9ycy5saWIvc2F3MTpsaWNlbmNlIjogIlNUSy00LjMiIH0seyAib3NjaWxsYXRvcnMubGliL3ZlcnNpb24iOiAiMC4zIiB9LHsgInBsYXRmb3JtLmxpYi9uYW1lIjogIkdlbmVyaWMgUGxhdGZvcm0gTGlicmFyeSIgfSx7ICJwbGF0Zm9ybS5saWIvdmVyc2lvbiI6ICIwLjIiIH0seyAic2lnbmFscy5saWIvbmFtZSI6ICJGYXVzdCBTaWduYWwgUm91dGluZyBMaWJyYXJ5IiB9LHsgInNpZ25hbHMubGliL29uZVBvbGVTd2l0Y2hpbmc6YXV0aG9yIjogIkpvbmF0YW4gTGlsamVkYWhsLCByZXZpc2VkIGJ5IERhcmlvIFNhbmZpbGlwcG8iIH0seyAic2lnbmFscy5saWIvb25lUG9sZVN3aXRjaGluZzpsaWNlbmNlIjogIlNUSy00LjMiIH0seyAic2lnbmFscy5saWIvdmVyc2lvbiI6ICIwLjMiIH1dLCJ1aSI6IFsgeyJ0eXBlIjogInZncm91cCIsImxhYmVsIjogImZhdXN0Z2VuLTgiLCJpdGVtcyI6IFsgeyJ0eXBlIjogImhzbGlkZXIiLCJsYWJlbCI6ICJkZWxheShtcykiLCJzaG9ydG5hbWUiOiAiZGVsYXlfbXMiLCJhZGRyZXNzIjogIi9mYXVzdGdlbi04L2RlbGF5X21zXyIsImluZGV4IjogNzIsImluaXQiOiAzMDAsIm1pbiI6IDEsIm1heCI6IDEwMDAsInN0ZXAiOiAxfSx7InR5cGUiOiAidnNsaWRlciIsImxhYmVsIjogImZlZWRiYWNrIiwic2hvcnRuYW1lIjogImZlZWRiYWNrIiwiYWRkcmVzcyI6ICIvZmF1c3RnZW4tOC9mZWVkYmFjayIsImluZGV4IjogMjAsIm1ldGEiOiBbeyAic3R5bGUiOiAia25vYiIgfV0sImluaXQiOiAwLjUsIm1pbiI6IDAsIm1heCI6IDIsInN0ZXAiOiAwLjAxfV19XX0AANc3AAAKAAAOjjcAAAsAAA6cDAAAAgAABpIMAAACAAAGiAwAAAIAAAZ+DAAAAgAABmoMAAACAAAGUwwAAAMAAAY/DAAAAgAABisMAAACAAAGFwwAAAIAAAYADAAAAgAABukLAAACAAAG0gsAAAIAAAa7CwAAAgAABqQLAAACAAAGmgsAAAwAAA6DCwAAAgAABm8LAAACAAAGWAsAAAIAAAZBCwAAAgAABioLAAACAAAGAwsAAAIAAAb1CgAAAgAABqIKAAAAAAAOIQoAAAIAAAbzCQAACQAADt8JAAADAAAGtAkAAAkAAA6hCQAAAgAABoIJAAACAAAG+gcAAAIAAAbfBwAAAgAABlgGAAACAAAGPQYAAAIAAAYdBgAAAgAABv0FAAACAAAG2AUAAAIAAAa4BQAAAgAABpgFAAACAAAGcwUAAAIAAAZQBQAAAgAABjAFAAACAAAGBwUAAAMAAAbkBAAAAgAABskEAAACAAAGoQQAAAIAAAaGBAAAAgAABmMEAAACAAAGNAQAAAIAAAYZBAAAAgAABvADAAADAAAGxQMAAAIAAAafAwAAAwAABoADAAACAAAGZQMAAAIAAAZKAwAAAgAABjMDAAACAAAGHwMAAAIAAAb/AgAAAwAABtYCAAADAAAGyAIAAAIAAAasAgAAAgAABpkCAAACAAAGhwIAAAIAAAZnAgAAAgAABlkCAAACAAAGNQIAAAIAAAYVAgAAAgAABvkBAAACAAAG0AEAAA0AAA7CAQAAAgAABp0BAAACAAAGhQEAAAIAAAYJAQAACAAADgEAAAAOBAAAMDwAAAAAAABmGgAADwEAAIAKAAAAAAAAHBoAAA8BAAAAAAAAAAAAAFgaAAAPAQAAsAoAAAAAAAAOGgAADwEAAJAKAAAAAAAAdRoAAA8BAACgCgAAAAAAAEQaAAAPAQAAEAAAAAAAAAAsGgAADwEAAHABAAAAAAAAgxoAAAEAAAAAAAAAAAAAAAkaAAABAAAAAAAAAAAAAACWGgAAAQAAAAAAAAAAAAAAnBoAAAEAAAAAAAAAAAAAAIwaAAABAAAAAAAAAAAAAACRGgAAAQAAAAAAAAAAAAAAAF97Im5hbWUiOiAiZmF1c3RnZW4tOCIsImZpbGVuYW1lIjogImZhdXN0Z2VuLTgiLCJ2ZXJzaW9uIjogIjIuNTAuNiIsImNvbXBpbGVfb3B0aW9ucyI6ICItbGFuZyBsbHZtIDE0LjAuNiAtZXMgMSAtbWNkIDE2IC1kb3VibGUgLWZ0eiAwIiwibGlicmFyeV9saXN0IjogWyIvVXNlcnMvZ3JlZy9Eb2N1bWVudHMvTWF4IDgvUGFja2FnZXMvZmF1c3RnZW4vZXh0ZXJuYWxzL21zcC9mYXVzdGdlbn4ubXhvL0NvbnRlbnRzL1Jlc291cmNlcy9zdGRmYXVzdC5saWIiLCIvVXNlcnMvZ3JlZy9Eb2N1bWVudHMvTWF4IDgvUGFja2FnZXMvZmF1c3RnZW4vZXh0ZXJuYWxzL21zcC9mYXVzdGdlbn4ubXhvL0NvbnRlbnRzL1Jlc291cmNlcy9jb21wcmVzc29ycy5saWIiLCIvVXNlcnMvZ3JlZy9Eb2N1bWVudHMvTWF4IDgvUGFja2FnZXMvZmF1c3RnZW4vZXh0ZXJuYWxzL21zcC9mYXVzdGdlbn4ubXhvL0NvbnRlbnRzL1Jlc291cmNlcy9vc2NpbGxhdG9ycy5saWIiLCIvVXNlcnMvZ3JlZy9Eb2N1bWVudHMvTWF4IDgvUGFja2FnZXMvZmF1c3RnZW4vZXh0ZXJuYWxzL21zcC9mYXVzdGdlbn4ubXhvL0NvbnRlbnRzL1Jlc291cmNlcy9tYXRocy5saWIiLCIvVXNlcnMvZ3JlZy9Eb2N1bWVudHMvTWF4IDgvUGFja2FnZXMvZmF1c3RnZW4vZXh0ZXJuYWxzL21zcC9mYXVzdGdlbn4ubXhvL0NvbnRlbnRzL1Jlc291cmNlcy9wbGF0Zm9ybS5saWIiLCIvVXNlcnMvZ3JlZy9Eb2N1bWVudHMvTWF4IDgvUGFja2FnZXMvZmF1c3RnZW4vZXh0ZXJuYWxzL21zcC9mYXVzdGdlbn4ubXhvL0NvbnRlbnRzL1Jlc291cmNlcy9ub2lzZXMubGliIiwiL1VzZXJzL2dyZWcvRG9jdW1lbnRzL01heCA4L1BhY2thZ2VzL2ZhdXN0Z2VuL2V4dGVybmFscy9tc3AvZmF1c3RnZW5+Lm14by9Db250ZW50cy9SZXNvdXJjZXMvZmlsdGVycy5saWIiLCIvVXNlcnMvZ3JlZy9Eb2N1bWVudHMvTWF4IDgvUGFja2FnZXMvZmF1c3RnZW4vZXh0ZXJuYWxzL21zcC9mYXVzdGdlbn4ubXhvL0NvbnRlbnRzL1Jlc291cmNlcy9hbmFseXplcnMubGliIiwiL1VzZXJzL2dyZWcvRG9jdW1lbnRzL01heCA4L1BhY2thZ2VzL2ZhdXN0Z2VuL2V4dGVybmFscy9tc3AvZmF1c3RnZW5+Lm14by9Db250ZW50cy9SZXNvdXJjZXMvc2lnbmFscy5saWIiLCIvVXNlcnMvZ3JlZy9Eb2N1bWVudHMvTWF4IDgvUGFja2FnZXMvZmF1c3RnZW4vZXh0ZXJuYWxzL21zcC9mYXVzdGdlbn4ubXhvL0NvbnRlbnRzL1Jlc291cmNlcy9iYXNpY3MubGliIl0sImluY2x1ZGVfcGF0aG5hbWVzIjogWyIvVXNlcnMvZ3JlZy9Eb2N1bWVudHMvTWF4IDgvUGFja2FnZXMvZmF1c3RnZW4vZXh0ZXJuYWxzL21zcC9mYXVzdGdlbn4ubXhvL0NvbnRlbnRzL1Jlc291cmNlcyIsIi9zaGFyZS9mYXVzdCIsIi91c3IvbG9jYWwvc2hhcmUvZmF1c3QiLCIvdXNyL3NoYXJlL2ZhdXN0IiwiLiJdLCJzaXplIjogNjYwMzg0LCJpbnB1dHMiOiAxLCJvdXRwdXRzIjogMiwic3JfaW5kZXgiOiAwLCJtZXRhIjogWyB7ICJhbmFseXplcnMubGliL2FtcF9mb2xsb3dlcl9hcjphdXRob3IiOiAiSm9uYXRhbiBMaWxqZWRhaGwsIHJldmlzZWQgYnkgUm9tYWluIE1pY2hvbiIgfSx7ICJhbmFseXplcnMubGliL25hbWUiOiAiRmF1c3QgQW5hbHl6ZXIgTGlicmFyeSIgfSx7ICJhbmFseXplcnMubGliL3ZlcnNpb24iOiAiMC4yIiB9LHsgImJhc2ljcy5saWIvbmFtZSI6ICJGYXVzdCBCYXNpYyBFbGVtZW50IExpYnJhcnkiIH0seyAiYmFzaWNzLmxpYi92ZXJzaW9uIjogIjAuOCIgfSx7ICJjb21waWxlX29wdGlvbnMiOiAiLWxhbmcgbGx2bSAxNC4wLjYgLWVzIDEgLW1jZCAxNiAtZG91YmxlIC1mdHogMCIgfSx7ICJjb21wcmVzc29ycy5saWIvY29tcHJlc3Npb25fZ2Fpbl9tb25vOmF1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImNvbXByZXNzb3JzLmxpYi9jb21wcmVzc2lvbl9nYWluX21vbm86Y29weXJpZ2h0IjogIkNvcHlyaWdodCAoQykgMjAxNC0yMDIwIGJ5IEp1bGl1cyBPLiBTbWl0aCBJSUkgPGpvc19jY3JtYS5zdGFuZm9yZC5lZHU+IiB9LHsgImNvbXByZXNzb3JzLmxpYi9jb21wcmVzc2lvbl9nYWluX21vbm86bGljZW5zZSI6ICJNSVQtc3R5bGUgU1RLLTQuMyBsaWNlbnNlIiB9LHsgImNvbXByZXNzb3JzLmxpYi9jb21wcmVzc29yX2xhZF9tb25vOmF1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImNvbXByZXNzb3JzLmxpYi9jb21wcmVzc29yX2xhZF9tb25vOmNvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMTQtMjAyMCBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NfY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJjb21wcmVzc29ycy5saWIvY29tcHJlc3Nvcl9sYWRfbW9ubzpsaWNlbnNlIjogIk1JVC1zdHlsZSBTVEstNC4zIGxpY2Vuc2UiIH0seyAiY29tcHJlc3NvcnMubGliL2NvbXByZXNzb3JfbW9ubzphdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJjb21wcmVzc29ycy5saWIvY29tcHJlc3Nvcl9tb25vOmNvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMTQtMjAyMCBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NfY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJjb21wcmVzc29ycy5saWIvY29tcHJlc3Nvcl9tb25vOmxpY2Vuc2UiOiAiTUlULXN0eWxlIFNUSy00LjMgbGljZW5zZSIgfSx7ICJjb21wcmVzc29ycy5saWIvbGltaXRlcl8xMTc2X1I0X21vbm86YXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiY29tcHJlc3NvcnMubGliL2xpbWl0ZXJfMTE3Nl9SNF9tb25vOmNvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMTQtMjAyMCBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NfY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJjb21wcmVzc29ycy5saWIvbGltaXRlcl8xMTc2X1I0X21vbm86bGljZW5zZSI6ICJNSVQtc3R5bGUgU1RLLTQuMyBsaWNlbnNlIiB9LHsgImNvbXByZXNzb3JzLmxpYi9uYW1lIjogIkZhdXN0IENvbXByZXNzb3IgRWZmZWN0IExpYnJhcnkiIH0seyAiY29tcHJlc3NvcnMubGliL3ZlcnNpb24iOiAiMC40IiB9LHsgImZpbGVuYW1lIjogImZhdXN0Z2VuLTgiIH0seyAiZmlsdGVycy5saWIvZmlyOmF1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImZpbHRlcnMubGliL2Zpcjpjb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zX2Njcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVycy5saWIvZmlyOmxpY2Vuc2UiOiAiTUlULXN0eWxlIFNUSy00LjMgbGljZW5zZSIgfSx7ICJmaWx0ZXJzLmxpYi9paXI6YXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiZmlsdGVycy5saWIvaWlyOmNvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMDMtMjAxOSBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NfY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJmaWx0ZXJzLmxpYi9paXI6bGljZW5zZSI6ICJNSVQtc3R5bGUgU1RLLTQuMyBsaWNlbnNlIiB9LHsgImZpbHRlcnMubGliL2xvd3Bhc3MwX2hpZ2hwYXNzMSI6ICJDb3B5cmlnaHQgKEMpIDIwMDMtMjAxOSBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NfY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJmaWx0ZXJzLmxpYi9sb3dwYXNzMF9oaWdocGFzczE6YXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiZmlsdGVycy5saWIvbG93cGFzczNlOmF1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImZpbHRlcnMubGliL2xvd3Bhc3MzZTpjb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zX2Njcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVycy5saWIvbG93cGFzczNlOmxpY2Vuc2UiOiAiTUlULXN0eWxlIFNUSy00LjMgbGljZW5zZSIgfSx7ICJmaWx0ZXJzLmxpYi9sb3dwYXNzNmU6YXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiZmlsdGVycy5saWIvbG93cGFzczZlOmNvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMDMtMjAxOSBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NfY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJmaWx0ZXJzLmxpYi9sb3dwYXNzNmU6bGljZW5zZSI6ICJNSVQtc3R5bGUgU1RLLTQuMyBsaWNlbnNlIiB9LHsgImZpbHRlcnMubGliL2xvd3Bhc3M6YXV0aG9yIjogIkp1bGl1cyBPLiBTbWl0aCBJSUkiIH0seyAiZmlsdGVycy5saWIvbG93cGFzczpjb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zX2Njcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVycy5saWIvbG93cGFzczpsaWNlbnNlIjogIk1JVC1zdHlsZSBTVEstNC4zIGxpY2Vuc2UiIH0seyAiZmlsdGVycy5saWIvbmFtZSI6ICJGYXVzdCBGaWx0ZXJzIExpYnJhcnkiIH0seyAiZmlsdGVycy5saWIvdGYxOmF1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImZpbHRlcnMubGliL3RmMTpjb3B5cmlnaHQiOiAiQ29weXJpZ2h0IChDKSAyMDAzLTIwMTkgYnkgSnVsaXVzIE8uIFNtaXRoIElJSSA8am9zX2Njcm1hLnN0YW5mb3JkLmVkdT4iIH0seyAiZmlsdGVycy5saWIvdGYxOmxpY2Vuc2UiOiAiTUlULXN0eWxlIFNUSy00LjMgbGljZW5zZSIgfSx7ICJmaWx0ZXJzLmxpYi90ZjFzOmF1dGhvciI6ICJKdWxpdXMgTy4gU21pdGggSUlJIiB9LHsgImZpbHRlcnMubGliL3RmMXM6Y29weXJpZ2h0IjogIkNvcHlyaWdodCAoQykgMjAwMy0yMDE5IGJ5IEp1bGl1cyBPLiBTbWl0aCBJSUkgPGpvc19jY3JtYS5zdGFuZm9yZC5lZHU+IiB9LHsgImZpbHRlcnMubGliL3RmMXM6bGljZW5zZSI6ICJNSVQtc3R5bGUgU1RLLTQuMyBsaWNlbnNlIiB9LHsgImZpbHRlcnMubGliL3RmMjphdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJmaWx0ZXJzLmxpYi90ZjI6Y29weXJpZ2h0IjogIkNvcHlyaWdodCAoQykgMjAwMy0yMDE5IGJ5IEp1bGl1cyBPLiBTbWl0aCBJSUkgPGpvc19jY3JtYS5zdGFuZm9yZC5lZHU+IiB9LHsgImZpbHRlcnMubGliL3RmMjpsaWNlbnNlIjogIk1JVC1zdHlsZSBTVEstNC4zIGxpY2Vuc2UiIH0seyAiZmlsdGVycy5saWIvdGYyczphdXRob3IiOiAiSnVsaXVzIE8uIFNtaXRoIElJSSIgfSx7ICJmaWx0ZXJzLmxpYi90ZjJzOmNvcHlyaWdodCI6ICJDb3B5cmlnaHQgKEMpIDIwMDMtMjAxOSBieSBKdWxpdXMgTy4gU21pdGggSUlJIDxqb3NfY2NybWEuc3RhbmZvcmQuZWR1PiIgfSx7ICJmaWx0ZXJzLmxpYi90ZjJzOmxpY2Vuc2UiOiAiTUlULXN0eWxlIFNUSy00LjMgbGljZW5zZSIgfSx7ICJmaWx0ZXJzLmxpYi92ZXJzaW9uIjogIjAuMyIgfSx7ICJtYXRocy5saWIvYXV0aG9yIjogIkdSQU1FIiB9LHsgIm1hdGhzLmxpYi9jb3B5cmlnaHQiOiAiR1JBTUUiIH0seyAibWF0aHMubGliL2xpY2Vuc2UiOiAiTEdQTCB3aXRoIGV4Y2VwdGlvbiIgfSx7ICJtYXRocy5saWIvbmFtZSI6ICJGYXVzdCBNYXRoIExpYnJhcnkiIH0seyAibWF0aHMubGliL3ZlcnNpb24iOiAiMi41IiB9LHsgIm5hbWUiOiAiZmF1c3RnZW4tOCIgfSx7ICJub2lzZXMubGliL25hbWUiOiAiRmF1c3QgTm9pc2UgR2VuZXJhdG9yIExpYnJhcnkiIH0seyAibm9pc2VzLmxpYi92ZXJzaW9uIjogIjAuNCIgfSx7ICJvc2NpbGxhdG9ycy5saWIvbGZfc2F3cG9zOmF1dGhvciI6ICJCYXJ0IEJyb3VucywgcmV2aXNlZCBieSBTdMOpcGhhbmUgTGV0eiIgfSx7ICJvc2NpbGxhdG9ycy5saWIvbGZfc2F3cG9zOmxpY2VuY2UiOiAiU1RLLTQuMyIgfSx7ICJvc2NpbGxhdG9ycy5saWIvbmFtZSI6ICJGYXVzdCBPc2NpbGxhdG9yIExpYnJhcnkiIH0seyAib3NjaWxsYXRvcnMubGliL3NhdzE6YXV0aG9yIjogIkJhcnQgQnJvdW5zIiB9LHsgIm9zY2lsbGF0b3JzLmxpYi9zYXcxOmxpY2VuY2UiOiAiU1RLLTQuMyIgfSx7ICJvc2NpbGxhdG9ycy5saWIvdmVyc2lvbiI6ICIwLjMiIH0seyAicGxhdGZvcm0ubGliL25hbWUiOiAiR2VuZXJpYyBQbGF0Zm9ybSBMaWJyYXJ5IiB9LHsgInBsYXRmb3JtLmxpYi92ZXJzaW9uIjogIjAuMiIgfSx7ICJzaWduYWxzLmxpYi9uYW1lIjogIkZhdXN0IFNpZ25hbCBSb3V0aW5nIExpYnJhcnkiIH0seyAic2lnbmFscy5saWIvb25lUG9sZVN3aXRjaGluZzphdXRob3IiOiAiSm9uYXRhbiBMaWxqZWRhaGwsIHJldmlzZWQgYnkgRGFyaW8gU2FuZmlsaXBwbyIgfSx7ICJzaWduYWxzLmxpYi9vbmVQb2xlU3dpdGNoaW5nOmxpY2VuY2UiOiAiU1RLLTQuMyIgfSx7ICJzaWduYWxzLmxpYi92ZXJzaW9uIjogIjAuMyIgfV0sInVpIjogWyB7InR5cGUiOiAidmdyb3VwIiwibGFiZWwiOiAiZmF1c3RnZW4tOCIsIml0ZW1zIjogWyB7InR5cGUiOiAiaHNsaWRlciIsImxhYmVsIjogImRlbGF5KG1zKSIsInNob3J0bmFtZSI6ICJkZWxheV9tcyIsImFkZHJlc3MiOiAiL2ZhdXN0Z2VuLTgvZGVsYXlfbXNfIiwiaW5kZXgiOiA3MiwiaW5pdCI6IDMwMCwibWluIjogMSwibWF4IjogMTAwMCwic3RlcCI6IDF9LHsidHlwZSI6ICJ2c2xpZGVyIiwibGFiZWwiOiAiZmVlZGJhY2siLCJzaG9ydG5hbWUiOiAiZmVlZGJhY2siLCJhZGRyZXNzIjogIi9mYXVzdGdlbi04L2ZlZWRiYWNrIiwiaW5kZXgiOiAyMCwibWV0YSI6IFt7ICJzdHlsZSI6ICJrbm9iIiB9XSwiaW5pdCI6IDAuNSwibWluIjogMCwibWF4IjogMiwic3RlcCI6IDAuMDF9XX1dfQBfZXhwAF9kZXN0cm95bXlkc3AAX2NsYXNzSW5pdG15ZHNwAF9pbnN0YW5jZUNvbnN0YW50c215ZHNwAF9pbnN0YW5jZUNsZWFybXlkc3AAX2NvbXB1dGVteWRzcABfYWxsb2NhdGVteWRzcABfZ2V0SlNPTm15ZHNwAF9fX2J6ZXJvAF9zaW4AX3RhbgBfZXhwMgBfbG9nMTAAAAAAAAA=",
									"machinecode_size" : 40364,
									"maxclass" : "newobj",
									"numinlets" : 1,
									"numoutlets" : 4,
									"outlettype" : [ "signal", "signal", "", "" ],
									"patching_rect" : [ 151.0, 218.0, 114.0, 22.0 ],
									"sample_format" : 1,
									"serial_number" : "C02D32LZPN5W64 bits",
									"sourcecode" : "import(\"stdfaust.lib\");\n\n//Average filter\nfilterLength = 500;\nmovingAvg(x) = par(i, filterLength, x@(i)):>_/filterLength;\n\n//Delay handle delay\ndelayAvg = delMs * (ma.SR/1000) : movingAvg;\ndelSec = delMs / 1000;\n\n//Measured tape speed= 8ips = 0.203 m/s\n//headDist = 0.203 * delSec; //[m] Not used\n\n//creating an angular frequency\npulse(freq) = os.lf_saw(freq) * (ma.PI);\n\n//phasenoise frequency is related to drift freq: i want smooth changes->freq has to be lower for \n//low freq drift while noise amplitude has to be higher \ndelDrift1 = sin(sinArg) * ampliSec * ma.SR //Capstan: Observed amplitude = 0.15 ms\nwith\n{\n    phaseNoise = (no.noise*5) : fi.lowpass6e(100); //adding noise to phase\n    freq = 26;\n    phase = ma.PI * 3/2 + phaseNoise;\n    sinArg = pulse(freq) + phase;\n    ampliSec = 0.00015;\n}; \ndelDrift2 = sin(sinArg) * ampliSec * ma.SR //Pinch wheel1: Observed amplitude = 0.15 ms\nwith\n{\n    phaseNoise = (no.noise*7) : fi.lowpass6e(35); //adding noise to phase\n    freq = 5;\n    phase = 0 + phaseNoise; //not visible in paper\n    sinArg = pulse(freq) + phase;\n    ampliSec = 0.00010 * delSec;\n};   \ndelDrift3 = sin(sinArg) * ampliSec * ma.SR //Pinch wheel2: Observed amplitude = 0.75 ms\nwith\n{\n    phaseNoise = (no.noise*20) : fi.lowpass6e(20); //adding noise to phase\n    freq = 2.5;\n    phase = ma.PI * 3/4 + phaseNoise;\n    sinArg = pulse(freq) + phase;\n    ampliSec = 0.00075 * delSec;\n};  \n\n//Noise\ndelNoise = (no.noise* noiseAmp * ma.SR) : LPfilter\nwith\n{\n    //Noise is proportional to head separation.\n    noiseAmp = 0.00075 * delSec;\n    LPfilter = fi.lowpass3e(70);\n};\n\n//0.75 is a factor to make the overall variation level similar to the paper\ndelayTotal = ((delDrift1 + delDrift2 + delDrift3 + delNoise)*0.75) + delayAvg;\n\n//Variable comb filter\npole = 0.9999;\nfilterDel = startFactor + ((endFactor-startFactor) * delSec) : int\nwith\n{   //48000 hardcoded SR, for some reason it does not work with ma.SR\n    firstNotchFreqStart = 7.5; //[Hz]\n    firstNotchFreqEnd = 2;\n    startFactor = 48000/(2 * firstNotchFreqStart);\n    endFactor = 48000/(2 * firstNotchFreqEnd);\n};\nffComb(delay, pole) = _<:_, _@delay*pole :> _/2; \n\ndelayProcessed = delayTotal : ffComb(filterDel, pole) : int;\n\n//Actual Delay + feedback\ndelayFunction(n, d, x) = x @ min(n, max(0, d));\nfeedback(x) = (x : tapeSat + x ~ (delay * repeats)) : filter\nwith\n{\n    tapeSat = co.limiter_1176_R4_mono;\n    delay = delayFunction(50000, delayProcessed, x);\n    filter = fi.lowpass(2,7000);\n};\n\n//Nonlinear distortion\n//amplifier(g) = ef.cubicnl_nodc(g, 0.1); //Not used\n\n//User params\ndelMs = hslider(\"delay(ms)\", 300, 1, 1000, 1);\nrepeats = vslider(\"feedback[style:knob]\", 0.5, 0, 2, 0.01);\n//echoLevel = vslider(\"Echo Volume[style:knob]\", 0.5, 0, 1, 0.01); //Not used\n\n/*Process*/\nprocess = feedback(_) <: _, _;",
									"sourcecode_size" : 2800,
									"text" : "faustgen~ echoPlex",
									"varname" : "faustgen-140487170756720",
									"version" : "1.62"
								}

							}
, 							{
								"box" : 								{
									"id" : "obj-2",
									"maxclass" : "newobj",
									"numinlets" : 2,
									"numoutlets" : 2,
									"outlettype" : [ "", "bang" ],
									"patching_rect" : [ 65.0, 601.0, 68.0, 22.0 ],
									"text" : "ll.pf ll.blues"
								}

							}
, 							{
								"box" : 								{
									"id" : "obj-6",
									"maxclass" : "newobj",
									"numinlets" : 2,
									"numoutlets" : 1,
									"outlettype" : [ "multichannelsignal" ],
									"patching_rect" : [ 65.0, 536.0, 80.0, 22.0 ],
									"text" : "mc.combine~"
								}

							}
, 							{
								"box" : 								{
									"id" : "obj-4",
									"maxclass" : "newobj",
									"numinlets" : 1,
									"numoutlets" : 2,
									"outlettype" : [ "signal", "signal" ],
									"patching_rect" : [ 141.0, 118.0, 74.0, 22.0 ],
									"text" : "mc.unpack~"
								}

							}
, 							{
								"box" : 								{
									"fontname" : "Arial",
									"fontsize" : 12.0,
									"id" : "obj-1",
									"maxclass" : "newobj",
									"numinlets" : 1,
									"numoutlets" : 2,
									"outlettype" : [ "", "" ],
									"patching_rect" : [ 582.0, 37.5, 78.0, 22.0 ],
									"save" : [ "#N", "thispatcher", ";", "#Q", "end", ";" ],
									"text" : "thispatcher",
									"varname" : "subTP"
								}

							}
, 							{
								"box" : 								{
									"comment" : "",
									"id" : "obj-5",
									"index" : 1,
									"maxclass" : "inlet",
									"numinlets" : 0,
									"numoutlets" : 1,
									"outlettype" : [ "multichannelsignal" ],
									"patching_rect" : [ 229.0, 36.0, 25.0, 25.0 ],
									"varname" : "in1"
								}

							}
, 							{
								"box" : 								{
									"comment" : "",
									"id" : "obj-9",
									"index" : 1,
									"maxclass" : "outlet",
									"numinlets" : 1,
									"numoutlets" : 0,
									"patching_rect" : [ 184.0, 570.0, 25.0, 25.0 ],
									"varname" : "out1"
								}

							}
 ],
						"lines" : [ 							{
								"patchline" : 								{
									"destination" : [ "obj-6", 1 ],
									"source" : [ "obj-3", 1 ]
								}

							}
, 							{
								"patchline" : 								{
									"destination" : [ "obj-6", 0 ],
									"source" : [ "obj-3", 0 ]
								}

							}
, 							{
								"patchline" : 								{
									"destination" : [ "obj-3", 0 ],
									"source" : [ "obj-4", 1 ]
								}

							}
, 							{
								"patchline" : 								{
									"destination" : [ "obj-3", 0 ],
									"source" : [ "obj-4", 0 ]
								}

							}
, 							{
								"patchline" : 								{
									"destination" : [ "obj-4", 0 ],
									"source" : [ "obj-5", 0 ]
								}

							}
, 							{
								"patchline" : 								{
									"destination" : [ "obj-3", 0 ],
									"source" : [ "obj-59", 0 ]
								}

							}
, 							{
								"patchline" : 								{
									"destination" : [ "obj-2", 0 ],
									"order" : 1,
									"source" : [ "obj-6", 0 ]
								}

							}
, 							{
								"patchline" : 								{
									"destination" : [ "obj-9", 0 ],
									"order" : 0,
									"source" : [ "obj-6", 0 ]
								}

							}
, 							{
								"patchline" : 								{
									"destination" : [ "obj-59", 0 ],
									"source" : [ "obj-61", 0 ]
								}

							}
, 							{
								"patchline" : 								{
									"destination" : [ "obj-3", 0 ],
									"source" : [ "obj-62", 0 ]
								}

							}
, 							{
								"patchline" : 								{
									"destination" : [ "obj-62", 0 ],
									"source" : [ "obj-63", 0 ]
								}

							}
, 							{
								"patchline" : 								{
									"destination" : [ "obj-61", 0 ],
									"source" : [ "obj-7", 0 ]
								}

							}
, 							{
								"patchline" : 								{
									"destination" : [ "obj-63", 0 ],
									"source" : [ "obj-8", 0 ]
								}

							}
 ]
					}
,
					"patching_rect" : [ 219.0, 78.0, 93.0, 22.0 ],
					"saved_object_attributes" : 					{
						"description" : "",
						"digest" : "",
						"globalpatchername" : "",
						"tags" : ""
					}
,
					"text" : "p echoPlexSUB",
					"textcolor" : [ 1.0, 0.207843137254902, 0.207843137254902, 1.0 ],
					"varname" : "sub"
				}

			}
, 			{
				"box" : 				{
					"color" : [ 0.0, 0.0, 0.0, 1.0 ],
					"fontname" : "Arial",
					"fontsize" : 12.0,
					"hidden" : 1,
					"id" : "obj-2",
					"maxclass" : "newobj",
					"numinlets" : 1,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"patching_rect" : [ 335.0, 66.0, 113.0, 22.0 ],
					"text" : "loadmess loadbang",
					"varname" : "loadmess"
				}

			}
, 			{
				"box" : 				{
					"active" : 					{
						"preset-ramp" : 0,
						"presets" : 0,
						"title_menu" : 0,
						"pres_menu" : 0,
						"tetris_menu" : 0,
						"master" : 0,
						"ll.blues" : 0,
						"ll.blues::levels" : 0,
						"ll.blues::outputs" : 0,
						"ll.blues::state" : 0
					}
,
					"color" : [ 0.0, 0.0, 0.0, 1.0 ],
					"fontname" : "Arial",
					"fontsize" : 12.0,
					"hidden" : 1,
					"id" : "obj-3",
					"maxclass" : "newobj",
					"numinlets" : 1,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"patching_rect" : [ 348.0, 87.0, 100.0, 22.0 ],
					"priority" : 					{
						"title_menu" : 2010,
						"pres_menu" : 2011,
						"tetris_menu" : 2012,
						"master" : 2013
					}
,
					"saved_object_attributes" : 					{
						"client_rect" : [ 1057, 45, 1440, 407 ],
						"parameter_enable" : 0,
						"parameter_mappable" : 0,
						"storage_rect" : [ 583, 69, 1034, 197 ]
					}
,
					"text" : "pattrstorage pat",
					"varname" : "pat"
				}

			}
, 			{
				"box" : 				{
					"color" : [ 0.0, 0.0, 0.0, 1.0 ],
					"fontname" : "Arial",
					"fontsize" : 12.0,
					"hidden" : 1,
					"id" : "obj-4",
					"maxclass" : "newobj",
					"numinlets" : 1,
					"numoutlets" : 2,
					"outlettype" : [ "", "" ],
					"patching_rect" : [ 335.0, 129.0, 107.0, 22.0 ],
					"save" : [ "#N", "thispatcher", ";", "#Q", "end", ";" ],
					"text" : "thispatcher",
					"varname" : "thispatcher"
				}

			}
, 			{
				"box" : 				{
					"color" : [ 0.0, 0.0, 0.0, 1.0 ],
					"fontname" : "Arial",
					"fontsize" : 12.0,
					"hidden" : 1,
					"id" : "obj-5",
					"maxclass" : "newobj",
					"numinlets" : 1,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"patching_rect" : [ 335.0, 150.0, 107.0, 22.0 ],
					"text" : "pattrmarker no",
					"varname" : "pattrmarker"
				}

			}
, 			{
				"box" : 				{
					"color" : [ 0.0, 0.0, 0.0, 1.0 ],
					"fontname" : "Arial",
					"fontsize" : 12.0,
					"hidden" : 1,
					"id" : "obj-6",
					"maxclass" : "newobj",
					"numinlets" : 1,
					"numoutlets" : 4,
					"outlettype" : [ "", "", "", "" ],
					"patching_rect" : [ 335.0, 171.0, 107.0, 22.0 ],
					"restore" : 					{
						"echoPlexDelayTime" : [ 300.0 ],
						"echoPlexFB" : [ 0.5 ],
						"master" : [ 0 ],
						"pres_menu" : [ "" ],
						"preset-ramp" : [ 0.0 ],
						"presets" : [ 0 ],
						"tetris_menu" : [ "" ],
						"title_menu" : [ "titlebar" ]
					}
,
					"text" : "autopattr autopattr",
					"varname" : "autopattr"
				}

			}
, 			{
				"box" : 				{
					"allowdrag" : 0,
					"annotation" : "title_menu - click on ppooll in the ho_st to find info about it",
					"bgcolor" : [ 1.0, 1.0, 1.0, 0.0 ],
					"bgfillcolor_color" : [ 1.0, 1.0, 1.0, 0.0 ],
					"bgfillcolor_color1" : [ 0.301961, 0.301961, 0.301961, 1 ],
					"bgfillcolor_color2" : [ 0.2, 0.2, 0.2, 1 ],
					"bgfillcolor_type" : "color",
					"fontname" : "Arial",
					"fontsize" : 12.0,
					"id" : "obj-8",
					"items" : [ "info", ",", "clientwindow", ",", "storagewindow", ",", "-", ",", "titlebar", ",", "close", ",", "back", ",", "grow", ",", "master", ",", "active_store", ",", "-", ",", "subpatch", ",", "actmaker" ],
					"maxclass" : "umenu",
					"numinlets" : 1,
					"numoutlets" : 3,
					"outlettype" : [ "int", "", "" ],
					"parameter_enable" : 0,
					"patching_rect" : [ 40.5, 0.0, 40.5, 22.0 ],
					"pattrmode" : 1,
					"textcolor" : [ 0.149, 0.149, 0.149, 1.0 ],
					"varname" : "title_menu"
				}

			}
, 			{
				"box" : 				{
					"allowdrag" : 0,
					"bgcolor" : [ 1.0, 1.0, 1.0, 0.0 ],
					"bgfillcolor_color" : [ 1.0, 1.0, 1.0, 0.0 ],
					"bgfillcolor_color1" : [ 0.301961, 0.301961, 0.301961, 1 ],
					"bgfillcolor_color2" : [ 0.2, 0.2, 0.2, 1 ],
					"bgfillcolor_type" : "color",
					"fontname" : "Arial",
					"fontsize" : 12.0,
					"id" : "obj-11",
					"ignoreclick" : 1,
					"items" : [ "-", ",", "write", ",", "clear!", ",", "TEXT" ],
					"maxclass" : "umenu",
					"numinlets" : 1,
					"numoutlets" : 3,
					"outlettype" : [ "int", "", "" ],
					"parameter_enable" : 0,
					"patching_rect" : [ 40.5, 0.0, 40.5, 22.0 ],
					"pattrmode" : 1,
					"textcolor" : [ 0.149, 0.149, 0.149, 1.0 ],
					"varname" : "pres_menu"
				}

			}
, 			{
				"box" : 				{
					"allowdrag" : 0,
					"bgcolor" : [ 1.0, 1.0, 1.0, 0.0 ],
					"bgfillcolor_color" : [ 1.0, 1.0, 1.0, 0.0 ],
					"bgfillcolor_color1" : [ 0.301961, 0.301961, 0.301961, 1 ],
					"bgfillcolor_color2" : [ 0.2, 0.2, 0.2, 1 ],
					"bgfillcolor_type" : "color",
					"fontname" : "Arial",
					"fontsize" : 12.0,
					"id" : "obj-13",
					"ignoreclick" : 1,
					"items" : "-",
					"maxclass" : "umenu",
					"numinlets" : 1,
					"numoutlets" : 3,
					"outlettype" : [ "int", "", "" ],
					"parameter_enable" : 0,
					"patching_rect" : [ 40.5, 0.0, 40.5, 22.0 ],
					"pattrmode" : 1,
					"textcolor" : [ 0.149, 0.149, 0.149, 1.0 ],
					"varname" : "tetris_menu"
				}

			}
, 			{
				"box" : 				{
					"annotation" : "drag here to move the window",
					"filename" : "ll.movewindow.js",
					"id" : "obj-15",
					"maxclass" : "jsui",
					"numinlets" : 1,
					"numoutlets" : 1,
					"outlettype" : [ "" ],
					"parameter_enable" : 0,
					"patching_rect" : [ 0.0, 0.0, 40.5, 14.0 ],
					"varname" : "master"
				}

			}
, 			{
				"box" : 				{
					"hidden" : 1,
					"id" : "obj-7",
					"maxclass" : "newobj",
					"numinlets" : 1,
					"numoutlets" : 3,
					"outlettype" : [ "", "", "" ],
					"patching_rect" : [ 348.0, 63.0, 100.0, 22.0 ],
					"restore" : [ "in(2)" ],
					"saved_object_attributes" : 					{
						"parameter_enable" : 0,
						"parameter_mappable" : 0
					}
,
					"text" : "pattr inputs~",
					"varname" : "inputs~"
				}

			}
 ],
		"lines" : [ 			{
				"patchline" : 				{
					"destination" : [ "obj-17", 0 ],
					"hidden" : 1,
					"source" : [ "obj-16", 1 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-43", 0 ],
					"hidden" : 1,
					"source" : [ "obj-16", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-43", 0 ],
					"hidden" : 1,
					"source" : [ "obj-17", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-1", 0 ],
					"hidden" : 1,
					"source" : [ "obj-2", 0 ]
				}

			}
, 			{
				"patchline" : 				{
					"destination" : [ "obj-1", 1 ],
					"hidden" : 1,
					"source" : [ "obj-3", 0 ]
				}

			}
 ],
		"dependency_cache" : [ 			{
				"name" : "actmaker.maxpat",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"type" : "JSON",
				"implicit" : 1
			}
, 			{
				"name" : "faustgen~.mxo",
				"type" : "iLaX"
			}
, 			{
				"name" : "ll.actmenu.maxpat",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"type" : "JSON",
				"implicit" : 1
			}
, 			{
				"name" : "ll.actname.maxpat",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"type" : "JSON",
				"implicit" : 1
			}
, 			{
				"name" : "ll.actnamehelper.maxpat",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"type" : "JSON",
				"implicit" : 1
			}
, 			{
				"name" : "ll.an.js",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/javascript",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/javascript",
				"type" : "TEXT",
				"implicit" : 1
			}
, 			{
				"name" : "ll.blues.maxpat",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/patchers/abstractions/filip/ll.blues",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/patchers/abstractions/filip/ll.blues",
				"type" : "JSON",
				"implicit" : 1
			}
, 			{
				"name" : "ll.createact8.js",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/javascript",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/javascript",
				"type" : "TEXT",
				"implicit" : 1
			}
, 			{
				"name" : "ll.inputmix.maxpat",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"type" : "JSON",
				"implicit" : 1
			}
, 			{
				"name" : "ll.movewindow.js",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/javascript",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/javascript",
				"type" : "TEXT",
				"implicit" : 1
			}
, 			{
				"name" : "ll.p.maxpat",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"type" : "JSON",
				"implicit" : 1
			}
, 			{
				"name" : "ll.pattr_ui.js",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/javascript",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/javascript",
				"type" : "TEXT",
				"implicit" : 1
			}
, 			{
				"name" : "ll.pf.maxpat",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"type" : "JSON",
				"implicit" : 1
			}
, 			{
				"name" : "ll.psto.maxpat",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"type" : "JSON",
				"implicit" : 1
			}
, 			{
				"name" : "ll.r.maxpat",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"type" : "JSON",
				"implicit" : 1
			}
, 			{
				"name" : "ll.r~.maxpat",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"type" : "JSON",
				"implicit" : 1
			}
, 			{
				"name" : "ll.shut.maxpat",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"type" : "JSON",
				"implicit" : 1
			}
, 			{
				"name" : "ll.strip#.maxpat",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"type" : "JSON",
				"implicit" : 1
			}
, 			{
				"name" : "ll.s~.maxpat",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"type" : "JSON",
				"implicit" : 1
			}
, 			{
				"name" : "ll.textsize.js",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/javascript",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/javascript",
				"type" : "TEXT",
				"implicit" : 1
			}
, 			{
				"name" : "ll.wsendback.js",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/javascript",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/javascript",
				"type" : "TEXT",
				"implicit" : 1
			}
, 			{
				"name" : "ll_fastforward.mxo",
				"type" : "iLaX"
			}
, 			{
				"name" : "ll_number.mxo",
				"type" : "iLaX"
			}
, 			{
				"name" : "n.maxpat",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/patchers/abstractions/filip",
				"type" : "JSON",
				"implicit" : 1
			}
, 			{
				"name" : "nblue.js",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/javascript",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/javascript",
				"type" : "TEXT",
				"implicit" : 1
			}
, 			{
				"name" : "pattrexists.mxo",
				"type" : "iLaX"
			}
, 			{
				"name" : "tetrishelp.js",
				"bootpath" : "~/Documents/Max 8/Packages/ppooll/javascript",
				"patcherrelativepath" : "../../../../../../Documents/Max 8/Packages/ppooll/javascript",
				"type" : "TEXT",
				"implicit" : 1
			}
 ],
		"autosave" : 0,
		"bgcolor" : [ 0.670588235294118, 0.717647058823529, 0.784313725490196, 1.0 ]
	}

}
